native/src/modules/common/components/TimeStamp.js, release-notes/unreleased/IGAPP-192-FixTypo.yml, web/src/modules/common/components/LastUpdateInfo.js, web/src/modules/common/components/__tests__/__snapshots__/LastUpdateInfo.spec.js.snap
=> IGAPP-192: No space after last update

.circleci/config.yml, .circleci/src/jobs/build_ios.yml, .circleci/src/jobs/build_web.yml, .circleci/src/jobs/bump_version.yml, .circleci/src/jobs/deliver_web.yml, .circleci/src/jobs/move_release_notes.yml, .circleci/src/jobs/notify_android.yml, .circleci/src/jobs/notify_ios.yml, .circleci/src/jobs/notify_web.yml, native/ios/fastlane/Fastfile, tools/constants.js, tools/create-jira-release, tools/git-version, tools/github-release, tools/move-release-notes, tools/next-version, tools/parse-release-notes
=> IGAPP-286: Test and fix deliveries

.circleci/config.yml, .circleci/src/workflows/triggered_native_development_delivery.yml
=> IGAPP-313: Add triggered_native_development_delivery.yml

.circleci/config.yml, .circleci/src/commands/notify_failed.yml, CODEOWNERS
=> IGAPP-312: Adjust codeowners

native/android/.idea/jarRepositories.xml, native/android/.idea/runConfigurations/Build_Integreat_Release.xml, native/android/.idea/runConfigurations/Build_Malte_Release.xml, native/android/.idea/runConfigurations/Clean.xml, native/android/.idea/runConfigurations/Start.xml, native/android/app/build.gradle, native/android/fastlane/Fastfile, native/package.json, package.json, yarn.lock
This also fixes:
* Crashes with iOS
* Problems with vector fonts
* Adds scripts to android project
=> IGAPP-95: Setup Android certificate

.circleci/config.yml, .circleci/src/jobs/deliver_android.yml, .circleci/src/jobs/deliver_ios.yml, .circleci/src/jobs/e2e_android.yml, .circleci/src/jobs/e2e_ios.yml, native/build-configs/BuildConfigType.js, native/build-configs/integreat/index.js, native/build-configs/malte/index.js, native/fastlane/Fastfile, native/src/modules/app/constants/__mocks__/buildConfig.js
=> IGAPP-317: Add appleId to build configs

web/build-configs/malte/index.js
=> IGAPP-33: Add itunes app id

.circleci/config.yml, .circleci/src/jobs/deliver_android.yml, .circleci/src/jobs/deliver_ios.yml, .circleci/src/jobs/e2e_android.yml, .circleci/src/jobs/e2e_ios.yml, native/build-configs/BuildConfigType.js, native/build-configs/integreat/index.js, native/build-configs/malte/index.js, native/fastlane/Fastfile, native/src/modules/app/constants/__mocks__/buildConfig.js
**ALREADY REVIEWED!** No need to review again, sorry for that. Accidentally merged the PR already, but as this would complicate reviewing the IGAPP-309 PR, I reverted it.
=> IGAPP-317: Add appleId to build config

native/.idea/runConfigurations/Run_release_on_Android.xml, native/.sentryclirc, native/fastlane/Fastfile, native/src/modules/app/initSentry.js
=> IGAPP-200: Set new sentry data

.circleci/config.yml, .circleci/src/commands/prepare_workspace.yml, .circleci/src/commands/restore_environment_variables.yml, .circleci/src/jobs/build_android.yml, .circleci/src/jobs/build_ios.yml, .circleci/src/jobs/deliver_android.yml, .circleci/src/jobs/deliver_ios.yml, .circleci/src/jobs/deliver_web.yml, .circleci/src/jobs/e2e_android.yml, .circleci/src/jobs/e2e_ios.yml, .circleci/src/jobs/move_release_notes.yml, .circleci/src/jobs/notify_android.yml, .circleci/src/jobs/notify_ios.yml, .circleci/src/jobs/notify_web.yml, native/fastlane/Fastfile, tools/parse-release-notes, version.json
=> IGAPP-327: Fix CI deliveries

native/src/modules/endpoint/sagas/loadCityContent.js, native/src/modules/endpoint/sagas/watchContentLanguageSwitch.js, native/src/modules/i18n/watchClearCity.js
=> IGAPP-210: Fix endless loading because of subscribing

native/src/modules/endpoint/sagas/loadCityContent.js, native/src/modules/endpoint/sagas/loadLanguages.js, native/src/modules/endpoint/sagas/watchContentLanguageSwitch.js, native/src/modules/i18n/watchClearCity.js, native/src/routes/categories/containers/CategoriesContainer.js, native/src/routes/dashboard/containers/DashboardContainer.js, native/src/routes/events/containers/EventsContainer.js, native/src/routes/news/containers/NewsContainer.js, native/src/routes/pois/containers/PoisContainer.js
=> IGAPP-331: Fix failure not shown because languages still loading

native/src/modules/categories/components/CategoryListItem.js, native/src/routes/landing/components/CityEntry.js, web/src/routes/categories/components/CategoryEntry.js, web/src/routes/landing/components/CityEntry.js, web/src/routes/landing/components/__tests__/__snapshots__/CityEntry.spec.js.snap
=> IGAPP-335: City search crashing for query `*`

native/src/modules/app/createAppContainer.js, native/src/modules/endpoint/hocs/withRouteCleaner.js, native/src/modules/theme/hocs/withTheme.js, native/src/routes/pdf/components/PDFViewModal.js
=> IGAPP-166: Change type from Component to NavigationComponent

native/src/routes/landing/components/CityEntry.js, native/src/routes/landing/components/CityGroup.js, native/src/routes/landing/components/CitySelector.js
=> IGAPP-204: Fix flex wrap for city selection

web/package.json, web/src/modules/layout/components/HeaderNavigationItem.js, web/src/modules/layout/components/__tests__/__snapshots__/HeaderNavigationItem.spec.js.snap, yarn.lock
=> IGAPP-323: Upgrade styled components

web/src/modules/i18n/containers/I18nProvider.js, web/src/modules/i18n/containers/__tests__/__snapshots__/I18nProvider.spec.js.snap
=> IGAPP-53: Feedback Dropdown cannot handle Special Characters

native/package.json, native/src/modules/categories/components/Categories.js, native/src/modules/categories/components/CategoryList.js, native/src/modules/categories/components/CategoryListContent.js, native/src/modules/common/components/Page.js, native/src/modules/common/onInternalLinkPress.js, native/src/modules/common/onLinkPress.js, native/src/modules/common/renderHtml.js, release-notes/unreleased/IGAPP-256-ImproveRemoteContent.yml, yarn.lock
=> IGAPP-256: Improve remote content in category list

native/android/.idea/runConfigurations/Build_Integreat_Release.xml, native/android/.idea/vcs.xml, native/android/app/build.gradle, native/android/app/proguard-rules.pro, native/src/modules/app/components/Navigator.js
=> IGAPP-163: Switch to Hermes

build-configs/BuildConfigType.js, build-configs/integreat/assets/mainImprint.js, build-configs/integreat/index.js, build-configs/malte/assets/mainImprint.js, build-configs/malte/index.js, build-configs/package.json, native/src/modules/app/constants/__mocks__/buildConfig.js, native/src/routes/settings/createSettingsSections.js, native/src/routes/settings/openPrivacyPolicy.js, native/tools/build-config, web/package.json, web/src/modules/app/containers/Switcher.js, web/src/modules/layout/components/GeneralFooter.js, web/src/modules/layout/components/LocationFooter.js, web/src/routes/main-disclaimer/components/MainDisclaimerPage.js, yarn.lock
=> IGAPP-266: Configurable imprint, about and privacy

native/android/fastlane/Fastfile, native/fastlane/Fastfile, native/ios/fastlane/Fastfile
=> IGAPP-361: Check fastlane parameters

native/src/modules/app/createAppContainer.js, native/src/modules/endpoint/hocs/withPayloadProvider.js, native/src/routes/intro/IntroContainer.js, native/src/routes/landing/containers/LandingContainer.js, release-notes/unreleased/IGAPP-166-ResolveFlowFixMeInNavigator.yml
see https://reactnavigation.org/docs/4.x/navigation-actions
=> IGAPP-197: Resolve Flowfixme in navigator

release-notes/unreleased/IGAPP-379-2nd-level-content-centering.yml, web/src/routes/categories/components/CategoryList.js, web/src/routes/categories/components/__tests__/__snapshots__/CategoryList.spec.js.snap
=> IGAPP-379: No automatic 2nd level centering

native/src/modules/app/StateType.js, native/src/modules/endpoint/reducers/__tests__/morphContentLanguage.spec.js, native/src/modules/endpoint/reducers/morphContentLanguage.js, native/src/routes/categories/containers/CategoriesContainer.js, native/src/routes/dashboard/containers/DashboardContainer.js, native/src/routes/events/containers/EventsContainer.js, native/src/routes/news/containers/NewsContainer.js, native/src/routes/pois/containers/PoisContainer.js, release-notes/unreleased/IGAPP-377-fix-change-unavailable-language.yml
=> IGAPP-377: LanguageNotAvailablePage not closing on language selection

README.md, docs/vscode.md, docs/windows-emulator.md, docs/windows-setup.md, native/docs/android-emulator-windows.md
=> IGAPP-381: Add vscode documentation

native/fastlane/Fastfile
=> IGAPP-389: Fix android delivery

api-client/package.json, api-client/src/models/DateModel.js, api-client/src/models/__tests__/DateModel.spec.js, native/src/modules/i18n/context/MomentContext.js, release-notes/unreleased/IGAPP-376-app-crashing.yml, web/src/routes/events/components/__tests__/EventListItem.spec.js, yarn.lock
=> IGAPP-376: Prevent app from crashing because of missing moment locale

native/src/modules/endpoint/hocs/withPayloadProvider.js
=> IGAPP-209: Fix state update warning in withPayloadProvider

locales/locales.json
https://issues.tuerantuer.org/browse/IGAPP-215
=> IGAPP-215: Changed the notFound key to "Page not found"

build-configs/integreat-e2e/index.js, build-configs/integreat-test-cms/index.js
=> IGAPP-319: Change application/bundle id for integreat-test-cms build config

release-notes/unreleased/IGAPP-57-external-links-same-tab.yml, web/.idea/integreat-app-web.iml, web/src/index.ejs, web/src/modules/common/components/CleanAnchor.js, web/src/modules/common/components/Tile.js, web/src/modules/common/components/__tests__/__snapshots__/Tile.spec.js.snap, web/src/modules/layout/components/__tests__/__snapshots__/GeneralFooter.spec.js.snap, web/src/modules/layout/components/__tests__/__snapshots__/LocationFooter.spec.js.snap, web/src/routes/news/components/TunewsDetailsFooter.js, web/src/routes/sprungbrett/containers/SprungbrettOfferPage.js, web/src/routes/sprungbrett/containers/__tests__/__snapshots__/SprungbrettOfferPage.spec.js.snap
=> IGAPP-57: External links should open in the same tab

.circleci/config.yml, .circleci/src/jobs/deliver_web.yml, web/.idea/vcs.xml
=> IGAPP-410: Delivering failing silently

web/tools/webpack.config.babel.js
=> IGAPP-412: Fix yarn start in windows

.circleci/config.yml, .circleci/src/commands/notify.yml, .circleci/src/commands/notify_failed.yml, .circleci/src/jobs/build_android.yml, .circleci/src/jobs/build_ios.yml, .circleci/src/jobs/build_web.yml, .circleci/src/jobs/bump_version.yml, .circleci/src/jobs/check_native.yml, .circleci/src/jobs/check_web.yml, .circleci/src/jobs/deliver_android.yml, .circleci/src/jobs/deliver_ios.yml, .circleci/src/jobs/deliver_web.yml, .circleci/src/jobs/e2e_android.yml, .circleci/src/jobs/e2e_ios.yml, .circleci/src/jobs/move_release_notes.yml, .circleci/src/jobs/notify_android.yml, .circleci/src/jobs/notify_ios.yml, .circleci/src/jobs/notify_web.yml, .circleci/src/workflows/commit.yml, .circleci/src/workflows/scheduled_native_development_delivery.yml, .circleci/src/workflows/scheduled_production_delivery.yml, .circleci/src/workflows/triggered_native_development_delivery.yml, .circleci/src/workflows/triggered_production_delivery.yml
=> IGAPP-437: Mattermost notifications

native/src/modules/endpoint/hocs/withPayloadProvider.js
=> IGAPP-336: New progress layout flow fix me

.circleci/config.yml, .circleci/src/commands/notify.yml, native/src/modules/common/__tests__/openExternalUrl.spec.js, native/src/modules/common/openExternalUrl.js, release-notes/unreleased/IGAPP-424-mailto-custom-tabs-crashing.yml
=> IGAPP-424: ChromeCustomTabs crashing on mailto links

web/README.md
=> IGAPP-XX add docs how to create a release build

native/src/modules/categories/components/Categories.js, native/src/modules/categories/components/CategoryList.js, native/src/modules/categories/components/CategoryListContent.js, native/src/modules/categories/components/CategoryListItem.js, native/src/modules/categories/components/SubCategoryListItem.js
=> IGAPP-429: Last update for inner categories

native/src/modules/categories/components/CategoryListContent.js
=> IGAPP-429: Use Date Context (fixes main)

README.md, build-configs/BuildConfigType.js, build-configs/README.md, native/docs/build-configs.md, native/docs/troubleshooting.md
=> IGAPP-40: Build config documentation

native/.idea/runConfigurations/Run_on_Android__aschaffenburg_.xml, native/.idea/runConfigurations/Start_packager__aschaffenburg_.xml, web/.idea/runConfigurations/Run__aschaffenburg_.xml, web/.idea/runConfigurations/Run__malte_.xml
=> IGAPP-444: Create intelliJ run configs

docs/cicd.md, native/docs/manual-builds.md, native/fastlane/Fastfile
=> IGAPP-455: Switch to App Store Connect API keys

translations/translations.json
I also updated the translations files which are currently in translations
=> IGAPP-104: Remove translation strings about Corona

api-client/src/endpoints/createSprungbrettJobsEndpoint.js, native/src/modules/app/constants/NavigationTypes.js, native/src/modules/endpoint/__tests__/loadFromEndpoint.spec.js, native/src/modules/endpoint/loadFromEndpoint.js, native/src/modules/error/components/Failure.js, native/src/modules/layout/components/Header.js, native/src/modules/navigation/__tests__/navigateToOffers.spec.js, native/src/modules/navigation/navigateToDisclaimer.js, native/src/modules/navigation/navigateToOffers.js, native/src/modules/theme/hocs/withTheme.js, native/src/routes/disclaimer/Disclaimer.js, native/src/routes/disclaimer/DisclaimerContainer.js, native/src/routes/offers/components/Offers.js, native/src/routes/offers/containers/OffersContainer.js, native/src/routes/offers/containers/__tests__/OffersContainer.spec.js, native/src/routes/sprungbrett/components/SprungbrettOffer.js, native/src/routes/sprungbrett/containers/SprungbrettOfferContainer.js, native/src/routes/sprungbrett/containers/__tests__/SprungbrettOfferContainer.spec.js, native/src/routes/wohnen/components/WohnenOffer.js, native/src/routes/wohnen/containers/WohnenOfferContainer.js, release-notes/unreleased/IGAPP-345-display-offers-loading.yml
This PR contains multiple changes:
* Fix displaying of errors for disclaimer, offers and sprungbrett
* Display error and disclaimer/offers/sprungbrettJobs during refreshing
* Refactoring and simplifying of routing to internal offers
=> IGAPP-345: Display offers during loading

README.md, build-configs/README.md, docs/cicd.md, native/README.md, native/docs/build-configs.md, web/README.md, web/docs/delivery.md
=> IGAPP-432 adjust documentation for aschaffenburg app

web/src/modules/i18n/containers/I18nProvider.js
=> IGAPP-478: Actually use override translations

native/src/modules/categories/components/CategoryListContent.js
=> IGAPP-502: Fix First-Level Content Conatining Lists

native/src/modules/common/components/ProgressSpinner.js
=> IGAPP-486: Fix loading spinner is cut at bottom

web/src/modules/layout/components/Header.js, web/src/modules/layout/components/HeaderActionItemDropDown.js
In this pull request i undid my changes for the iOS bug ticket, these are no longer necessary due to updated polyfills.
=> IGAPP-508: Fix navigation while hoovering

native/src/modules/layout/components/Header.js, native/src/modules/layout/containers/HeaderContainer.js
=> IGAPP-492: Proposal

native/src/modules/common/components/NavigationTiles.js
=> IGAPP-425: Linebreaks in navigation items on small devices

native/ios/Integreat.xcodeproj/project.pbxproj
=> IGAPP-547: Fix varlea round font usage on iOS

.circleci/config.yml, .circleci/src/workflows/scheduled_native_promotion.yml, .circleci/src/workflows/triggered_production_delivery.yml
=> IGAPP-567: Dont do production releases for aschaffenburg

native/src/modules/app/StoreActionType.js, native/src/modules/endpoint/reducers/__tests__/cityContentReducer.spec.js, native/src/modules/endpoint/reducers/cityContentReducer.js, native/src/routes/categories/containers/CategoriesContainer.js, native/src/routes/events/containers/EventsContainer.js, native/src/routes/news/containers/NewsContainer.js, native/src/routes/pois/containers/PoisContainer.js
=> IGAPP-531: Replace specific actions with generic clear route action

api-client/src/endpoints/__tests__/createTrackingEndpoint.spec.js, api-client/src/endpoints/createTrackingEndpoint.js, api-client/src/tracking/index.js, native/src/modules/common/__tests__/openExternalUrl.spec.js, native/src/modules/common/openExternalUrl.js, native/src/modules/layout/__tests__/HeaderContainer.spec.js, native/src/modules/layout/containers/HeaderContainer.js, native/src/modules/navigation/__tests__/navigateToLink.spec.js, native/src/modules/navigation/navigateToLink.js
=> IGAPP-561: Send signal if link is clicked

native/ios/Integreat.xcodeproj/project.pbxproj
We no longer generate ku as we now use kmr. This will be adressed in a future issue.
=> IGAPP-553: Merge me to fix Xcode!

release-notes/unreleased/IGAPP-552-add-dari.yml, translations/src/config.js
=> IGAPP-552: Add dari

release-notes/unreleased/IGAPP-620-toolbar-poking-through-feedback.yml, web/src/modules/feedback/components/FeedbackModal.js
=> IGAPP-620: Fix toolbar poking through feedback

api-client/src/endpoints/__tests__/createFeedbackEndpoint.spec.js, api-client/src/endpoints/createFeedbackEndpoint.js, release-notes/unreleased/IGAPP-621-feedback-on-dashboard-fails.yml, web/src/modules/app/route-configs/CategoriesRouteConfig.js
=> IGAPP-621: Fix feedback type on dashboard

tools/parse-release-notes
See https://chat.tuerantuer.org/digitalfabrik/pl/jkpe5wqsrpg3zkpwshasjoat4c for more information what this is about.
=> IGAPP-xxx: Fix issue linking in mattermost

native/src/modules/common/components/ProgressSpinner.tsx
=> IGAPP 634: Replace image params with props-object to prevent ts error

web-ts/package.json
=> IGAPP-622: Readd path-to-regexp

CODEOWNERS, native/README.md, native/docs/troubleshooting.md
=> IGAPP-xxx: Adjust troubleshooting and add andy as codeowner

api-client/package.json, api-client/src/@types/sanitize-html-react.d.ts, api-client/src/endpoints/__tests__/createDisclaimerEndpoint.spec.ts, api-client/src/endpoints/__tests__/createEventsEndpoint.spec.ts, api-client/src/endpoints/__tests__/createLocalNewsElementEndpoint.spec.ts, api-client/src/endpoints/__tests__/createLocalNewsEndpoint.spec.ts, api-client/src/endpoints/__tests__/createPOIsEndpoint.spec.ts, api-client/src/endpoints/__tests__/createTunewsElementEndpoint.spec.ts, api-client/src/endpoints/__tests__/createTunewsEndpoint.spec.ts, api-client/src/endpoints/createDisclaimerEndpoint.ts, api-client/src/endpoints/createEventsEndpoint.ts, api-client/src/endpoints/createLocalNewsElementEndpoint.ts, api-client/src/endpoints/createLocalNewsEndpoint.ts, api-client/src/endpoints/createPOIsEndpoint.ts, api-client/src/endpoints/createTunewsElementEndpoint.ts, api-client/src/endpoints/createTunewsEndpoint.ts, api-client/src/mapping/__tests__/mapCategoryJson.spec.ts, api-client/src/mapping/mapCategoryJson.ts, yarn.lock
=> IGAPP-619: Revert IGAPP-619

native/docs/required-dependencies.md, native/package.json, web/docs/required-dependencies.md, yarn.lock
=> IGAPP-698: Fix pdf by readding dependencies

native/src/App.tsx, release-notes/unreleased/IGAPP-699-webview-crashing.yml
=> IGAPP-699: Webview crashing the app

web/src/components/Header.tsx
=> IGAPP-696: Fix navigation header overflow

api-client/src/maps/index.ts, web/src/components/MapView.tsx, web/src/routes/PoisPage.tsx
you can double-check bounding box here, since maybe the points are not set perfectly but for a test its fine
https://geojson.io/#map=11/48.3489/10.7302
```json
{
"type": "FeatureCollection",
"features": [
{
"type": "Feature",
"properties": {},
"geometry": {
"type": "Point",
"coordinates": [
10.7377731,
48.2745231
]
}
},
{
"type": "Feature",
"properties": {},
"geometry": {
"type": "Point",
"coordinates": [
10.9271413,
48.4473535
]
}
}
]
}
```
=> IGAPP-537: Move BBox web

e2e-tests/tsconfig.json, e2e-tests/web/capabilities.ts, e2e-tests/web/test/pageobjects/categories.page.ts, e2e-tests/web/test/pageobjects/dashboard.page.ts, e2e-tests/web/test/specs/navigateToCategories.e2e.ts, e2e-tests/web/test/utils/helpers.ts, e2e-tests/web/wdio.conf.ts
=> IGAPP-467: Add e2e test for categories

native/src/components/MapView.tsx, native/src/routes/Pois.tsx, release-notes/unreleased/IGAPP-540-show-pois-native.yml
=> IGAPP-540: Display Pois on Map - Native

native/src/components/CategoryList.tsx, native/src/components/CategoryListContent.tsx, native/src/components/NativeHtml.tsx, native/src/components/NewsDetail.tsx, native/src/components/NewsListItem.tsx, native/src/components/Page.tsx, native/src/components/TimeStamp.tsx, native/src/components/__tests__/CategoryListContent.spec.tsx, native/src/components/__tests__/NativeHtml.spec.tsx, native/src/components/__tests__/NewsDetail.spec.tsx, native/src/components/__tests__/NewsListItem.spec.tsx, native/src/components/__tests__/TimeStamp.spec.tsx, native/src/routes/News.tsx, native/src/testing/wrapWithTheme.tsx, release-notes/unreleased/IGAPP-744-fix-alignment-news-continue-button.yml, version.json
…n news and refactor theming and translation in news components
=> IGAPP-744: Fix News continue button has wrong direction

native/src/routes/Pois.tsx, native/src/routes/PoisContainer.tsx
=> IGAPP-751: Map Refresh Bug

native/ios/Integreat.xcodeproj/project.pbxproj, native/ios/Podfile.lock, release-notes/unreleased/IGAPP-678-hungarian.yml, translations/translations.json
=> IGAPP-678: Add hungarian

native/src/components/SiteHelpfulBox.tsx, release-notes/unreleased/IGAPP-750-SiteHelpFull-Icons.yml
=> IGAPP-750: rm icon background

api-client/src/Endpoint.ts, api-client/src/__tests__/Endpoint.spec.ts
=> IGAPP-781: Throw FetchError if response.json() fails

release-notes/unreleased/IGAPP-794-remove-gradient-local-news.yml, web/src/components/LocalNewsList.tsx, web/src/components/NewsListItem.tsx, web/src/components/TuNewsList.tsx
=> IGAPP-794: Remove weird background of news

native/src/hocs/withPayloadProvider.tsx, native/src/hooks/__tests__/useClearRouteOnClose.spec.tsx, native/src/hooks/useClearRouteOnClose.ts, native/src/routes/CategoriesContainer.tsx, native/src/routes/DashboardContainer.tsx, native/src/routes/EventsContainer.tsx, native/src/routes/LandingContainer.tsx, native/src/routes/NewsContainer.tsx, native/src/routes/PoisContainer.tsx, release-notes/unreleased/IGAPP-825-language-change-broken.yml
=> IGAPP-825: Language change broken

.circleci/config.yml, .circleci/src/workflows/triggered_production_delivery.yml, translations/store-translations/aschaffenburg.json, translations/tools/manage.ts
=> IGAPP-803: Fix aschaffenburg store translations

e2e-tests/web/test/specs/navigateToDashboard.e2e.ts, e2e-tests/web/test/specs/navigateToNewLocation.e2e.ts, e2e-tests/web/test/specs/navigateToSearchResults.e2e.ts
Fixes the error which was merged in https://github.com/Integreat/integreat-app/pull/497
=> IGAPP-XX: Fix typing error in web e2e test

e2e-tests/native/test/specs/changeLanguage.e2e.ts, e2e-tests/native/wdio-browserstack.conf.ts
=> IGAPP-844: Wait until loading disappears

build-configs/common/theme/fonts.ts, native/src/components/NativeHtml.tsx, release-notes/unreleased/IGAPP-869-tunews-detailsview-padding.yml, web/src/components/RemoteContent.tsx
Please test native & web(mobile) the figures containing the images
Example Article: http://localhost:9000/testumgebung/de/news/tu-news/471
Tested on web(chrome), ios & android
=> IGAPP-869: Tunews detailsview padding

api-client/src/endpoints/createDisclaimerEndpoint.ts, api-client/src/endpoints/createEventsEndpoint.ts, api-client/src/endpoints/createPOIsEndpoint.ts, api-client/src/mapping/mapCategoryJson.ts, api-client/src/models/CategoriesMapModel.ts, api-client/src/models/CategoryModel.ts, api-client/src/models/PageModel.ts, api-client/src/models/__tests__/CategoryModel.spec.ts, api-client/src/models/__tests__/PageModel.spec.ts
=> IGAPP-279: Normalize path in models

native/src/routes/CityNotCooperating.tsx, web/src/routes/CityNotCooperatingPage.tsx
=> IGAPP-908: Linebreak in missing cities not necessary

native/ios/Integreat.xcodeproj/project.pbxproj
=> IGAPP-112: Enable bitcode for debug

tools/git-version
=> IGAPP-5: Prevent automated version bumps on other branches than main

native/src/components/CitySelector.tsx
=> IGAPP-915: Filter cities in developer friendly builds

build-configs/integreat/assets/cityNotCooperatingTemplate.ts, release-notes/unreleased/IGAPP-900-fix-text.yml
=> IGAPP-925: Fix text for city not cooperating template

native/android/app/build.gradle, native/android/app/src/main/res/drawable/rn_edit_text_material.xml, native/android/app/src/main/res/values/styles.xml, native/android/build.gradle, native/android/gradle.properties, native/android/gradle/wrapper/gradle-wrapper.properties, native/package.json, native/src/@types/react-native-static-server.d.ts, native/src/components/StaticServerProvider.tsx, native/tsconfig.json, yarn.lock
=> IGAPP-928: Upgrade react native to v0.67.2

release-notes/unreleased/IGAPP-937-add-ukrainian-support.yml, translations/src/config.ts
=> IGAPP-937: Add support for ukrainian

web/src/components/ShelterInformation.tsx, web/src/components/ShelterInformationSection.tsx
=> IGAPP-944: Make mail and phone clickable and fix quarter

web/src/components/ShelterInformationSection.tsx
=> IGAPP-944: Adjusted styles for extended view

version.json
=> IGAPP-944: Release web app to production

tools/github-authentication.ts
=> IGAPP-949: Fix github authentication

web/src/components/ShelterInformationSection.tsx
Minor styling fixes like shelter icon alignment
=> IGAPP-953: Shelter Icon Alignment

api-client/src/Endpoint.ts, api-client/src/MapParamsToBody.ts, api-client/src/endpoints/createShelterContactEndpoint.ts, api-client/src/index.ts, api-client/src/models/ShelterModel.ts, api-client/src/types.ts, translations/translations.json, web/src/components/Feedback.tsx, web/src/components/ShelterContactRequestForm.tsx, web/src/components/ShelterDetail.tsx, web/src/components/ShelterInformation.tsx, web/src/components/ShelterInformationSection.tsx, web/src/components/ShelterListItem.tsx, web/src/components/TextButton.tsx, web/src/components/TextInput.tsx
=> IGAPP-950: Add shelter contact form

.circleci/config.yml, .circleci/src/jobs/notify_android.yml, .circleci/src/jobs/notify_ios.yml, .circleci/src/jobs/notify_web.yml
=> IGAPP-987: Publish release info to renamed channel

build-configs/integreat/index.ts
Tested that Pois are still hidden for other cities than testumgebung on web and native.
=> IGAPP-1003: Enable pois

native/src/routes/Pois.tsx
=> IGAPP-999: Remove jumping to snappoint when selecting poi from list

native/ios/Integreat.xcodeproj/project.pbxproj, native/ios/Integreat.xcodeproj/xcshareddata/xcschemes/aschaffenburg.xcscheme
=> IGAPP-1001: Use the target name as product name

native/react-native.config.js
=> IGAPP-1002: Correct parsing of env variables

build-configs/BuildConfigType.ts, build-configs/aschaffenburg/index.ts, build-configs/index.ts, build-configs/integreat/index.ts, build-configs/malte/index.ts, build-configs/obdach/index.ts, build-configs/tools/manage.ts, web/src/index.ejs, web/tools/webpack.config.ts
=> IGAPP-1013: Make android and ios in build config optional

native/src/components/PoiDetails.tsx
=> IAGPP-1009: Fix address clipboard copy

native/src/components/NavigationTiles.tsx
=> IGAPP-1022 and IGAPP-1007: Proposal

build-configs/integreat/mainImprint.ts
=> IGAPP-1053: Update mainImprint

api-client/src/maps/index.ts, api-client/src/models/__tests__/PoiModel.spec.ts, api-client/src/utils/__tests__/geoJson.spec.ts, release-notes/unreleased/IGAPP-1028-poi-markers-pixelated.yml
1. http://localhost:9000/testumgebung/de/locations
2. Zoom on the map and check if markers are still pixelated
Tested on web & ios
=> IGAPP-1028: Poi markers pixelated

web/src/components/PageDetail.tsx
=> IGAPP-1071: Remove todo and unused logic from PageDetail

release-notes/unreleased/IGAP-1066-back-navigation-after-redirect-impossible.yml, web/src/RootSwitcher.tsx, web/src/routes/CategoriesPage.tsx
=> IGAPP-1066: Back navigation after redirects impossible

.eslintrc.js, native/src/routes/__tests__/SearchModal.spec.tsx, native/src/sagas/__tests__/watchFetchCategory.spec.ts, native/src/sagas/__tests__/watchFetchCities.spec.ts, native/src/sagas/__tests__/watchFetchEvent.spec.ts, native/src/utils/__tests__/openExternalUrl.spec.ts, native/src/utils/openExternalUrl.ts, tools/git-version.ts, tools/github-release.ts, tools/move-release-notes.ts
=> IGAPP-1054: Only await thenable

native/run, tools/git-version.ts, tools/github-release.ts, tools/jira-release.ts, tools/manage-metadata.ts, tools/move-release-notes.ts, translations/tools/manage.ts
Seems like it always have to first be command, then options and only then the action. Otherwise the options are just lost. Only tested commands where this was the case last time :/
=> IGAPP-1081: Fix failing tools

release-notes/unreleased/IGAPP-1074-nl.yml, translations/src/config.ts
=> IGAPP-1074: Add support for Dutch

tools/jira-release.ts
=> IGAPP-1082: Fix failing create jira release

release-notes/unreleased/IGAPP-1084-add-dutch-translations.yml, release-notes/unreleased/IGAPP-983-wrong-text-alignment.yml, translations/translations.json
=> IGAPP-1084: Add dutch translations

docs/e2e-tests.md, e2e-tests/native/test/helpers/Selector.ts, e2e-tests/native/test/specs/navigateToSearchResult.e2e.ts, e2e-tests/native/wdio-ios.conf.ts, e2e-tests/package.json, native/docs/e2e-testing.md
=> IGAPP-1072: Show exerpt fix ios e2e

native/src/routes/PDFViewModal.tsx, release-notes/unreleased/IGAPP-1087-fix-pdf-on-android.yml
=> IGAPP-1087: Fix PDF on Android

web/src/components/LocationLayout.tsx
=> IGAPP-xx: Go live chatbot munich

web/src/components/FeedbackModal.tsx
This is just a quick fix. Wrote the details in the ticket.
=> IGAPP-1117: Feedback broken quick fix

native/src/components/CategoryList.tsx, native/src/components/CategoryListItem.tsx, native/src/components/__tests__/CategoryListItem.spec.tsx, native/src/routes/SearchModal.tsx, release-notes/unreleased/IGAPP-1119-excerpts-match.yml, web/src/components/CategoryEntry.tsx, web/src/components/CategoryList.tsx, web/src/components/__tests__/CategoryEntry.spec.tsx, web/src/routes/SearchPage.tsx
=> IGAPP-1119: Show excerpt around search match

native/src/routes/PDFViewModal.tsx, release-notes/unreleased/IGAPP-1113-maps-link-in-pdf.yml, translations/translations.json
Kreis Olpe -> Beratungsstellen und Hilfsangebote -> Beratungsstellen Integration und Migration -> open PDF -> klick on GMaps Icon
Tested on android & ios
=> IGAPP-1113: Map link in pdf

release-notes/unreleased/IGAPP-1126-event-title-and-content-overflow.yml, web/src/components/EventListItem.tsx, web/src/components/ListItem.tsx, web/src/components/SprungbrettListItem.tsx
=> IGAPP-1126: Event title and overflow

web/src/components/NavigationBarScrollContainer.tsx, web/src/hooks/useCallbackRef.ts, web/src/hooks/useRefWithCallback.ts
=> IGAPP-1064: Proposal for refactoring

native/docs/troubleshooting.md
This pull request doesn't belong to an issue on our bugtracker, it's just two small additions to our Troubleshooting guide that I would have needed :)
=> IGAPP-xxx: Addition to troubleshooting

native/docs/troubleshooting.md
Forgot to add the steps to the table of contents. Oooops!
=> IGAPP-xxx: Add new troubleshooting points to the table of contents

CODEOWNERS
This pull request adds me as a code owner so that I get requests for reviews automatically :)
=> IGAPP-xxx: Add Leandra to code owners

web/src/components/BottomActionSheet.tsx
Happened due to refactoring
https://github.com/digitalfabrik/integreat-app/pull/793
Pls test web mobile that the handleBar is shown when a poi was selected.
No release notes due to fixing before it occurs in next version :)
http://localhost:9000/testumgebung/de/locations/cafe-t%C3%BCr-an-t%C3%BCr
=> IGAPP-1157: Fix handle bar poi detail

native/android/app/src/main/AndroidManifest.xml, native/android/build.gradle
=> IGAPP-XXX: Upgrade sdk version to 31

.circleci/config.yml, .circleci/src/commands/notify.yml, CODEOWNERS, translations/CODEOWNERS
=> IGAPP-xxx: Update code owners and circleci notifications

native/src/utils/renderHtml.ts, release-notes/unreleased/IGAPP-1187-fix-line-breaks-external-links.yml, web/src/components/RemoteContent.tsx
This pull request belongs to the issue https://issues.tuerantuer.org/browse/IGAPP-1187. When testing the marker for external links, I had only tested ones that were on a new line anyway, but we also have some that are in flow text.
To test:
Broken version on https://integreat.app/aichach-friedberg/de/recht-und-finanzen/aufenthalt-und-asylverfahren (under Sandra Mühlpointner)
Fixed version on http://localhost:9000/aichach-friedberg/de/recht-und-finanzen/aufenthalt-und-asylverfahren
=> IGAPP-1187: Fix for External Links

release-notes/unreleased/IGAPP-1183-portugese-czech.yaml, translations/src/config.ts
=> IGAPP-1183: Add support for portuguese and czech

native/src/contexts/AppContextProvider.tsx, native/src/hooks/useSubscribePushNotifications.ts, native/src/utils/DatabaseConnector.ts, native/src/utils/DefaultDataContainer.ts
=> IGAPP-636: Subscribe to push notifications and update last usage

release-notes/unreleased/IGAPP-1190-purpose-location-usage.yaml, translations/translations.json
Since Apple requires these string, i added it even we don't use it
Reference chat
https://chat.tuerantuer.org/digitalfabrik/pl/jyeszgxcebfmmcxs6p5ne4afnc
=> IGAPP-1190: Purpose location usage

.circleci/config.yml, .circleci/src/commands/notify.yml
=> IGAPP-xxx: Fix mattermost mentions

.circleci/config.yml, .circleci/src/jobs/build_android.yml, .circleci/src/jobs/build_ios.yml
=> IGAPP-1115: Fix apk and ipa url

web/src/routes/__tests__/PoisPage.spec.tsx
=> IGAPP-1153: Use url slug in poi test

native/src/utils/DatabaseConnector.ts, release-notes/unreleased/IGAPP-1203-fix-timeslots.yaml, translations/translations.json
Please test if you can open location with timeslots f.e. on Android and iOS
Tested on both devices
https://integreat.app/testumgebung/de/locations/cafe-t%C3%BCr-an-t%C3%BCr
=> IGAPP-1203: Fix timeslots

native/src/components/List.tsx, release-notes/unreleased/IGAPP-1201-fix-sticky-footer.yaml
=> IGAPP-1201: Fix sticky footer in Event List

native/src/components/Snackbar.tsx, native/src/components/SnackbarContainer.tsx, native/src/hooks/useLoadWithCache.ts, native/src/hooks/useNavigate.ts, native/src/hooks/useNavigateToDeepLink.ts, native/src/hooks/useNavigateToLink.ts, native/src/hooks/useSnackbar.ts, native/src/utils/PushNotificationsManager.ts, native/src/utils/createSettingsSections.ts, native/src/utils/openExternalUrl.ts
=> IGAPP-328: Increase foreground push notification duration

.eslintrc.js, native/src/Navigator.tsx, native/src/__tests__/Navigator.spec.tsx, native/src/components/Snackbar.tsx, native/src/components/SnackbarContainer.tsx, native/src/hooks/__tests__/useNavigateToDeepLink.spec.tsx, native/src/hooks/useLoadWithCache.ts, native/src/hooks/useNavigate.ts, native/src/hooks/useNavigateToDeepLink.ts, native/src/hooks/useNavigateToLink.ts, native/src/hooks/useSnackbar.ts, native/src/utils/PushNotificationsManager.ts, native/src/utils/createSettingsSections.ts, native/src/utils/openExternalUrl.ts, release-notes/unreleased/IGAPP-1085-news-not-opened.yaml
=> IGAPP-1085: News not opened upon click on push notifications

native/src/utils/DatabaseConnector.ts, release-notes/unreleased/IGAPP-1211-wrong-temporarily-closed-cache.yaml
Testumgebung -> Map -> check poi that is not marked as temp closed in cms f.e. "Tür an Tür Cafe"
=> IGAPP-1211: Wrong temporarily closed cache

.circleci/config.yml, .circleci/src/jobs/build_web.yml, .circleci/src/jobs/bump_version.yml, .circleci/src/jobs/check.yml, .circleci/src/jobs/deliver_web.yml, .circleci/src/jobs/e2e_web.yml, .circleci/src/jobs/move_release_notes.yml, .circleci/src/jobs/notify_android.yml, .circleci/src/jobs/notify_ios.yml, .circleci/src/jobs/notify_web.yml, .circleci/src/jobs/promote_web.yml
=> IGAPP-1227: fix pipeline e2e-web by downgrading node version

api-client/src/models/EventModel.ts, api-client/src/models/__tests__/EventModel.spec.ts, api-client/src/utils/index.ts, release-notes/unreleased/IGAPP-1229-fix-time-export-of-events.yml
Fixed endDate and added correct timezones to startDate & endDate
Pls export an event and import to a calendar und check times, title, description
http://localhost:9000/testumgebung/de/events/zweite-testveranstaltung
=> IGAPP-1229: Times of events will be exported correctly

web/src/components/OpeningHours.tsx
=> IGAPP-1188: Keep collapsble state of opening hours

api-client/src/endpoints/__tests__/createCategoriesEndpoint.spec.ts, api-client/src/endpoints/__tests__/createCategoryChildrenEndpoint.spec.ts, api-client/src/endpoints/__tests__/createCategoryContentEndpoint.spec.ts, api-client/src/endpoints/__tests__/createCategoryParentsEndpoint.spec.ts, api-client/src/endpoints/__tests__/createCitiesEndpoint.spec.ts, api-client/src/endpoints/__tests__/createDisclaimerEndpoint.spec.ts, api-client/src/endpoints/__tests__/createEventsEndpoint.spec.ts, api-client/src/endpoints/__tests__/createFeedbackEndpoint.spec.ts, api-client/src/endpoints/__tests__/createLanguagesEndpoint.spec.ts, api-client/src/endpoints/__tests__/createLocalNewsElementEndpoint.spec.ts, api-client/src/endpoints/__tests__/createLocalNewsEndpoint.spec.ts, api-client/src/endpoints/__tests__/createOffersEndpoint.spec.ts, api-client/src/endpoints/__tests__/createPOIsEndpoint.spec.ts, api-client/src/endpoints/createCategoriesEndpoint.ts, api-client/src/endpoints/createCategoryChildrenEndpoint.ts, api-client/src/endpoints/createCategoryContentEndpoint.ts, api-client/src/endpoints/createCategoryParentsEndpoint.ts, api-client/src/endpoints/createCitiesEndpoint.ts, api-client/src/endpoints/createDisclaimerEndpoint.ts, api-client/src/endpoints/createEventsEndpoint.ts, api-client/src/endpoints/createFeedbackEndpoint.ts, api-client/src/endpoints/createLanguagesEndpoint.ts, api-client/src/endpoints/createLocalNewsElementEndpoint.ts, api-client/src/endpoints/createLocalNewsEndpoint.ts, api-client/src/endpoints/createOffersEndpoint.ts, api-client/src/endpoints/createPOIsEndpoint.ts, release-notes/unreleased/IGAPP-1215-trailing-slashes-for-api-endpoints.yaml
Do I need release notes for this?
=> 1215: add trailing slashes to api url

.circleci/config.yml, .circleci/src/commands/restore_cocoa_pods_cache.yml, .circleci/src/jobs/build_ios.yml, .circleci/src/jobs/deliver_ios.yml, .circleci/src/jobs/promote_ios.yml, native/ios/Gemfile.lock, native/ios/Integreat.xcodeproj/project.pbxproj, native/ios/Integreat.xcworkspace/xcshareddata/swiftpm/Package.resolved, native/ios/Podfile, native/ios/Podfile.lock
=> IGAPP-1221: Upgrade Xcode in CI

native/src/components/Header.tsx, native/src/components/__tests__/Header.spec.tsx, native/src/routes/__tests__/LocalNews.spec.tsx, native/src/routes/__tests__/TuNews.spec.tsx, release-notes/unreleased/IGAPP-919-back-navigation-title.yml
This pull request belongs to the issue https://issues.tuerantuer.org/browse/IGAPP-919
=> IGAPP-919: Add the title of the previous route to the header

build-configs/malte/index.ts, release-notes/unreleased/IGAPP-1275-Activate-pois-malte.yml
http://localhost:9000/guestrowsued/de/locations
=> IGAPP-1275: Activate pois for malte

release-notes/unreleased/IGAPP-1257-Add-missing-focus.yml, version.json, web/src/components/Collapsible.tsx, web/src/components/FacetInput.tsx, web/src/components/FacetToggle.tsx, web/src/components/Layout.tsx, web/src/components/SearchInput.tsx
Just use tab to navigate through the page
=> IGAPP-1257: Add missing focus

native/src/components/NativeHtml.tsx, release-notes/unreleased/IGAPP-1286-local-news-RTL.yml
=> IGAPP-1286: Fix text alignment of local news

native/docs/i18n.md
=> IGAPP-1259: Add more documentation about ui and content language

native/src/Navigator.tsx, native/src/components/Header.tsx, native/src/components/__tests__/Header.spec.tsx, native/src/hooks/useHeader.tsx, native/src/routes/CategoriesContainer.tsx, release-notes/unreleased/IGAPP-1293-back-button-flickering.yml
=> IGAPP-1293: Fix back button flickering

native/src/components/Header.tsx, native/src/components/SearchHeader.tsx, native/src/components/StatusBar.tsx, native/src/components/ThemedSearchBar.tsx, native/src/components/TransparentHeader.tsx
=> IGAPP-1304: Improve some colors for ios

web/src/components/PoisDesktop.tsx, web/src/components/PoisMobile.tsx, web/src/hooks/usePoiFeatures.ts, web/src/routes/PoisPage.tsx
=> IGAPP-1234: Proposal

native/android/app/src/main/java/tuerantuer/app/integreat/MainActivity.java
=> IGAPP-1326: Fix runtime exception

web/src/components/Layout.tsx
can only be reproduced on webnext
=> IGAPP-1328: Toolbar not sticky

.circleci/config.yml, .circleci/src/jobs/deliver_web.yml, .circleci/src/jobs/notify_web.yml, .circleci/src/jobs/promote_web.yml, build-configs/obdach/index.ts, yarn.lock
Note: DataPrivacy & About pages are not available yet and don't work
=> IGAPP-1337: Adjust build config to new domain

native/ios/Integreat/Info.plist
Ios Simulator: go to testumgebung -> map -> tür an tür cafe > click on telephone or mail
=> IGAPP-1344: Ios url schemes

native/src/components/SpaceBetween.ts, release-notes/unreleased/IGAPP-1336-description-placing.yml
This pull request belongs to the issue https://issues.tuerantuer.org/browse/IGAPP-1336 .
Important for testing: please check that the other uses of Page and SpaceBetween look the same.
=> IGAPP-1336: Fix description space

release-notes/unreleased/IGAPP-1354-remove-empty-space-top.yml, web/src/components/Layout.tsx, web/src/routes/LocalNewsPage.tsx
This pull request belongs to the issue https://issues.tuerantuer.org/browse/IGAPP-1354
=> IGAPP-1354: Remove empty space at top of small screens

build-configs/obdach/mainImprint.ts
=> IGAPP-1342: Main imprint

native/src/components/FeedbackButtons.tsx
This bug only occurs on android please test it there!
=> IGAPP-1363: No box shadow rating

native/src/components/AddressInfo.tsx, native/src/components/CalendarChoiceModal.tsx, native/src/components/CategoryListItem.tsx, native/src/components/CityEntry.tsx, native/src/components/EastereggImage.tsx, native/src/components/FeedbackButtons.tsx, native/src/components/ListItem.tsx, native/src/components/MapsAttribution.tsx, native/src/components/NavigationTile.tsx, native/src/components/NewsHeader.tsx, native/src/components/NewsListItem.tsx, native/src/components/Pagination.tsx, native/src/components/PoiDetailRow.tsx, native/src/components/PoiListItem.tsx, native/src/components/SearchListItem.tsx, native/src/components/SelectorItem.tsx, native/src/components/SettingItem.tsx, native/src/components/StyledLink.ts, native/src/components/SubCategoryListItem.tsx, native/src/components/Tile.tsx, native/src/components/Touchable.ts, native/src/components/base/Pressable.tsx, native/src/routes/JpalTracking.tsx, native/src/routes/Licenses.tsx, release-notes/unreleased/IGAPP-1366-use-pressable.yml
In favor of #1004, sorry you have to review again :/ Replacing react-native-elements button component will be done in #1003.
=> IGAPP-1366: Unify onPress behavior by using Pressable everywhere

api-client/src/maps/index.ts, native/src/constants/layers.ts, web/src/constants/layers.ts
=> IGAPP-1350: Add offset to poi active symbol

api-client/src/endpoints/createEventsEndpoint.ts
=> 2382: Hide expired events

web/src/components/PoiFilters.tsx, web/src/components/base/Checkbox.tsx
Ensure that no checkbox/label id is used twice not just assuming the label will be unique.
- Pass an id instead of just using the label as id.
Related to #2393.
---
=> 2115: Ensure unique checkbox id

release-notes/unreleased/2424-location-category-labels-truncated.yml, web/src/components/StyledSmallViewTip.tsx, web/src/components/base/ToggleButton.tsx
-Increase button size to allow multiple lines for labels
#2424
=> 2424: increase filter button size. Make labels multiline

native/src/components/BottomActionsSheet.tsx
=> 2433: Bottom sheet hardly scrollable on ios

release-notes/unreleased/2462-disclaimer-link-wrong.yml, web/src/components/CityContentHeader.tsx, web/src/components/Header.tsx, web/src/components/KebabActionItemLink.tsx, web/src/components/KebabMenu.tsx, web/src/components/__tests__/Header.spec.tsx
Fix the link to the disclaimer.
Use the city code instead of the city name to construct the link.
None
Fixes: #2462.
---
=> 2462: Fix disclaimer link

native/src/routes/Events.tsx, translations/translations.json, web/src/routes/EventsPage.tsx
Add translations for #2031.
Add translations for #2031 and rename `date` to `date_one`.
None.
Fixes: None.
---
=> 2031: Add translations

native/src/routes/Pois.tsx
Just removing a comment that we don't need anymore (the color is correct already)
=> Remove outdated comment

.circleci/config.yml, .circleci/src/jobs/build_ios.yml, .circleci/src/jobs/deliver_ios.yml, .circleci/src/jobs/promote_ios.yml
Updating XCode to version 15.0.1
Fixes: #2551 
---
=> 2551: Update XCode to 15

api-client/src/maps/index.ts, api-client/src/utils/__tests__/geoJson.spec.ts, api-client/src/utils/geoJson.ts, native/src/components/MapView.tsx, native/src/constants/layers.ts, release-notes/unreleased/2504-zoom-cluster-click.yml, web/src/components/MapView.tsx, web/src/constants/layers.ts
As a user i want to zoom in if i click on a map cluster.
- add function that zooms on click of a cluster
Fixes: #2504
Just realized that we have different animations on web & native. On native it may make sense to decrease the animation duration
Tested on ios, chrome & firefox
=> 2504: Zoom cluster click

translations/translations.json
Added translations for portugues.
Fixes: https://github.com/digitalfabrik/integreat-app/issues/2445
=> Add portugues translations

web/src/components/Feedback.tsx, web/src/components/FeedbackButtons.tsx, web/src/components/FeedbackContainer.tsx, web/src/components/FeedbackSearch.tsx, web/src/components/FeedbackToolbarItem.tsx, web/src/components/InputSection.tsx, web/src/components/Note.tsx, web/src/components/__tests__/Feedback.spec.tsx, web/src/components/__tests__/FeedbackContainer.spec.tsx, web/src/components/base/InputSection.tsx
Refactor feedback on web by reusing shared logic from api-client and extracting things to components.
I chose not to merge Feedback and FeedbackContainer as both are still ~ 100 lines.
- Extract shared feedback logic with web to api-client
- Extract code to new separate components (InputSection, Note, FeedbackButtons)
- Adjust styling
- Align code with native
None.
Fixes: #2524.
---
=> 2524: Refactor feedback web

native/src/components/RemoteContent.tsx, native/src/utils/renderHtml.ts
This refactors renderHtml a little to make things clearer and easier to use and read.
- Use allowedIframeSources from build config
- Add comments on how to use parameters
- Use const and let instead of var
- Use speaking functions for IIFEs (Immediately Invoked Function Expression)
- Use JSON.stringify bevor logging errors
None.
Fixes: #2587.
---
=> 2587: Refactor renderHtml and add comments

native/src/components/Consent.tsx, native/src/components/ConsentSection.tsx
Fix duplicated state. The problem was basically updating a react state with the same object which doesn't trigger a rerender, even though a property was change.
=> 1213: Proposal to fix duplicated state

release-notes/unreleased/2618-fix-external-link.yml, web/src/components/RemoteContent.tsx
Fix displaying of external link icon
Readd width and height for external link icon.
None.
Fixes: #2618.
---
=> 2618: Fix external link icon

native/src/components/List.tsx
Removed the content flex of the List.
Maybe we should trigger a beta today directly with this fix.
- Maybe something with the pois does not work as expected, compare to https://github.com/digitalfabrik/integreat-app/pull/2640
Fixes: #2660
---
=> 2660: Fix news not scrollable

native/src/routes/SearchModal.tsx, shared/hooks/useSearch.ts, web/src/hooks/useAllPossibleSearchResults.ts, web/src/routes/SearchPage.tsx
Fix flickering of search results for web.
- Return null if minisearch is not yet initialized
- Fix types
None.
Fixes: None.
---
=> 2727: Fix flickering

build-configs/obdach/index.ts
Adjusted the filename.
Fixes: #2758 
---
=> 2758: Fix broken header icon for obdach

release-notes/unreleased/2824-add-slovakian.yml, translations/src/config.ts
Add support for slovakian
Add slovakian (`sk`) to our config.
App translations will be done separtely.
None.
Partly fixes: #2824.
---
=> 2824: Add support for slovakian

release-notes/unreleased/2824-add-oromo.yml, translations/src/config.ts
Add support for Oromo language.
Add Omoro to config with language code `omr` and `rtl: false`.
None.
Partly fixes: #2846.
---
=> 2846: Add Oromo language

build-configs/package.json, tools/package.json, translations/package.json, web/package.json
The mobile layout is broken on many pages
- remove `sideEffects:false`
- hopefully none
Fixes: #2837
---
I removed all sideEffects flag because i dunno what else issue they make cause
=> 2837: Mobile layout broken

web/package.json, web/src/components/OpeningEntry.tsx, web/src/components/OpeningHours.tsx, yarn.lock
Here an proposal with a proper library. i would tend to replace our own tooltip component. But you can also adjust the existing one to make it multiline
Some styling issues still occur -> draft
=> 2457-proposal

web/src/components/ChatContainer.tsx, web/src/components/ChatSecurityInformation.tsx
Just fixing two small layout bugs, mainly to not cover the footer with the chat in small screens on RTL languages.
Fixes: #2849 
---
=> 2849: Fix small layout bugs

translations/translations.json
Add oromo translations and remove linebreaks and invalid escapes.
- Add oromo translations
- Remove backslashs and linebreaks
No more fixed linebreaks in chat data protection.
Fixes: #2824
---
=> 2725: Add oromo translations and remove linebreaks

shared/api/endpoints/__tests__/createLocalNewsEndpoint.spec.ts
@steffenkleinle Something along these lines is what I was thinking. Just to have a small example of what the API response looks like and what we do with it.
=> 2732: Add available language to the test

build-configs/obdach/index.ts, translations/override-translations/obdach.json
Override meta description for search engine purposes
- override meta description
- import overrides in buildConfig
- none
Fixes: #2891
---
=> 2891: Override meta description

README.md, assets/README.md, docs/contributing.md, docs/conventions.md
Add svg documentation and update documentation.
- Add svg documentation
- Update our documentation in a few places where it was outdated
- None.
None.
Fixes: #2954 
---
=> 2954: Add svg documentation and update documentation

release-notes/unreleased/2982-add-romani.yml, translations/README.md, translations/src/config.ts, translations/translations.json
Add support for romani language.
- Add romani to our translation config
- Initiate translation to romani
- Romani translations will be added at a later point.
http://localhost:9000/testumgebung/rom should work as expected without errors.
Partly fixes: #2982 
---
=> 2982: Add support for romani language

native/src/components/Header.tsx
Fix header titles.
- Use the correct title and translate route names
- None.
Please test thoroughly and move around in the app.
Especially go to category leaf pages and event/news details and open the settings from there and in different places.
Fixes: #3017 
---
=> 3017: Fix header title

CODEOWNERS
=> Remove Steffi from codeowners

native/src/components/Header.tsx, native/src/components/TtsContainer.tsx, native/src/components/TtsPlayer.tsx, native/src/hooks/useTtsPlayer.ts
=> 2916: TTS android proposal

docs/contributing.md, docs/conventions.md
Add branch naming and clarify commit messages and PR names conventions
N/A
N/A
Fixes: N/A
---
=> Add branch naming and clarify commit messages and PR names conventions

.circleci/config.yml, .circleci/src/jobs/deliver_android.yml, .circleci/src/jobs/deliver_ios.yml
Fix fastlane delivery
- Fix fastlane installation
N/A
Hope the CI succeeds :crossed_fingers: 
Fixes: N/A
---
=> Fix fastlane delivery

native/android/fastlane/Fastfile, native/ios/fastlane/Fastfile
Fix fastlane metadata delivery
- Fix fastlane metadata paths to fix delivery
- N/A
Hope that the CI succeeds now :crossed_fingers: 
Fixes: N/A
---
=> Fix fastlane metadata delivery

release-notes/unreleased/3098-vietnamese.yml, translations/src/config.ts, translations/translations.json
Add support and translations for vietnamese.
N/A
Check that you can select vietnamese (http://localhost:9000/testumgebung/vi) and smoke test the translations.
Fixes: #3098
---
=> 3098: Add vietnamese

docs/contributing.md
Clarify release note docs.
- Clarify release note docs
N/A
N/A
Fixes: N/A
---
=> Clarify release note docs

.idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml
Use code style from .prettierrc in IntelliJ
- Use code style from .prettierrc in IntelliJ
N/A
N/A
Fixes: N/A
---
=> Use code style from .prettierrc in IntelliJ

build-configs/aschaffenburg/index.ts
Disable push notifications for aschaffenburg.
N/A
Install aschaffenburg and navigate to settings and see that there is no more option for push notifications.
Fixes: #3090
---
=> 3090: Disable push notifications for aschaffenburg

SECURITY.md
Add link to our full security & vulnerability reporting policy.
- Update SECURITY.md
- None
None
None
---
=> Add link to detailed security policy

translations/translations.json, web/src/components/ChatContainer.tsx, web/src/components/ChatContentWrapper.tsx, web/src/components/ChatMenu.tsx, web/src/components/ChatModal.tsx, web/src/components/CityContentLayout.tsx, web/src/components/__tests__/ChatContainer.spec.tsx, web/src/hooks/useWindowDimensions.ts
Remove redundant chat minimize button and fix chat button position on top of footer.
- Remove the chat minimizing as it basically does the same as close
- Replace the close icon
- Fix the chat button position to be (vertically) above the footer
N/A
Check the position of the chat button in multiple screen sizes (with and without reloading).
Test closing the chat (both on small and big viewports).
Fixes: #3178
---
=> 3178: Remove chat minimize button and fix chat button position

.circleci/config.yml, .circleci/src/commands/notify.yml
Fix mattermost notifications for @lunars97 and @bahaaTuffaha.
N/A
N/A
Fixes: N/A
---
=> Fix mattermost notifications

.circleci/config.yml, .circleci/src/jobs/deliver_android.yml
Fix delivery by using correct working directory.
N/A
N/A
Fixes: N/A
---
=> Fix delivery

.circleci/config.yml, .circleci/src/jobs/deliver_ios.yml, e2e-tests/shared/constants.ts, e2e-tests/web/test/specs/navigateToSearchResults.e2e.ts, package.json, tools/package.json, tools/yarn.lock, yarn.lock
Actually fix delivery.
- Fixing e2e web search tests (probably caused by #3266
- Bump app-toolbelt to fix parsing of release notes
- Use correct working directory for ios
N/A
N/A
Fixes: N/A
---
=> Actually fix delivery (hopefully?)

build-configs/aschaffenburg/index.ts, build-configs/integreat/index.ts, build-configs/malte-test-cms/index.ts, build-configs/malte/index.ts, build-configs/obdach/index.ts, native/src/constants/__mocks__/buildConfig.ts, release-notes/unreleased/2821-enable-tts.yml, web/src/components/TtsContainer.tsx, web/src/components/__mocks__/easy-speech.tsx, web/src/components/__tests__/TtsContainer.spec.tsx, web/src/utils/tts.tsx
Enable tts for production integreat, malte, aschaffenburg and obdach.
Also improve the voice quality on MacOS for German and English.
- Enable the tts feature for all build configs
- Improve voice quality on MacOS for German and English by setting default languages
- Extract some tts logic to utils
Other languages might still not use an optimal voice per default. If you experience this, please let me know. However, my smoke test did not reveal any serious problems with other languages.
Test tts for different languages, operating systems and browsers.
Fixes: #2821
Fixes: #3174
---
=> 2821, 3174: Enable tts and improve voice quality on macos

docs/contributing.md
Add contributing docs for translations
N/A
N/A
Fixes: N/A
---
=> Add contributing docs for translations

package.json, tools/package.json, tools/yarn.lock, yarn.lock
Actually bump app-toolbelt after the version was bumped in the package.json.
N/A
N/A
Fixes: N/A
---
=> Actually bump app-toolbelt

.circleci/config.yml, .circleci/src/jobs/bump_version.yml, .circleci/src/workflows/native_beta_delivery.yml, .circleci/src/workflows/native_production_delivery.yml, .circleci/src/workflows/web_beta_delivery.yml, .circleci/src/workflows/web_production_delivery.yml
Currently all tags (all, web, native, android, ios) are created for every delivery since we don't pass the platforms parameter.
- Pass the corresponding platform to the git release script
N/A
N/A
Fixes: N/A
---
=> Only create a single tag per delivery

native/src/routes/SearchModal.tsx, native/src/routes/__tests__/SearchModal.spec.tsx, release-notes/unreleased/3326-search-order.yml, release-notes/unreleased/3326-search.yml, shared/hooks/__tests__/useSearch.spec.tsx, shared/hooks/useSearch.ts, shared/index.ts, shared/jest.config.ts, shared/package.json, shared/utils/__tests__/search.spec.ts, shared/utils/search.ts, web/src/routes/SearchPage.tsx, web/src/routes/__tests__/SearchPage.spec.tsx, yarn.lock
This PR fixes search results for multi-word queries and includes some other search improvements.
- Only show search results that match all search terms
- Order search results by relevance (search score)
- Only show German results that are not found in the users language
- Add tests
N/A
Check out the search (http://localhost:9000/muenchen/en/search) and search for:
- Cafe Bellevue di Monaco (only relevant search results should be returned)
- Familiennachzug (only german results that are not included in the content language should be returned)
Fixes: #3326
---
=> 3326: Fix search results for multi-word queries

release-notes/unreleased/3353-translations-thai.yml, translations/README.md, translations/translations.json, web/src/components/Chat.tsx
Add translations in Thai and other missing translations
- Add Thai translations
- Add missing translations
N/A
Smoke test the new translations and review the changes.
Fixes: #3353
---
=> 3353: Add translations in Thai and other missing translations

build-configs/common/theme/colors.ts, web/src/components/CityContentHeader.tsx, web/src/components/GeneralHeader.tsx, web/src/components/HeaderActionItemDropDown.tsx, web/src/components/HeaderActionItemLink.tsx, web/src/components/HeaderLanguageSelectorItem.tsx, web/src/components/__tests__/Header.spec.tsx, web/src/components/__tests__/HeaderActionItemDropDown.spec.tsx
I added a small PR to migrate the header links and dropdowns completely to mui.
-
The ripple effect does not yet work correctly for the language dropdown as we set a custom color there.
N/A
Fixes: N/A
---
=> [Proposal] 3321: Migrate header links and dropdown to mui

package.json, yarn.lock
Remove outdated axios resolution.
- Remove outdated axios resolution (see discussion here #https://github.com/digitalfabrik/integreat-app/pull/3408#issuecomment-3143849231)
N/A
N/A
Fixes: N/A
---
=> Remove outdated axios resolution

build-configs/aschaffenburg/index.ts
Just enabling push notifications for Aschaffenburg again
Fixes #3464 
---
=> 3464: Enable push notifications for Aschaffenburg

translations/src/config.ts, translations/translations.json
Adding the Indonesian translations and removing Hausa since the municipality decided against it (https://chat.tuerantuer.org/digitalfabrik/pl/u1bchwerwpr5uqz9h7rfp545ra)
Fixes: #3439 
---
=> 3439: Indonesian translations

web/src/__mocks__/useDimensions.ts, web/src/components/ChatContainer.tsx, web/src/hooks/__tests__/useDimensions.spec.ts, web/src/hooks/useDimensions.ts
The boolean dimensions where configured wrongly.
- Set the correct dimensions
- Adjust text size of bottom navigation on xsmall screens
N/A
N/A
Fixes: N/A
---
=> Fix dimensions
