native/package.json
yarn.lock

The issue claimed, that the package uses deprecated features, but those seem to be removed starting version 3.0.0. Convince yourself if you don't believe me though 😸

IGAPP-94: Update react-native-image-zoom-viewer

---

native/babel.config.js

IGAPP-375: Fix babel transpile error in decamelize npm

---

native/src/modules/common/components/RemoteContent.js
native/src/routes/external-offer/components/ExternalOffer.js
web/src/index.ejs

See discussion here: https://tuerantuer.slack.com/archives/CDV9QF1GA/p1587050318013000
This seems not to happen anymore, but we think disabling is still the best option.
API reference: https://github.com/react-native-webview/react-native-webview/blob/d4ab332891af2242e663ac2e25f4aa3317945399/docs/Reference.md#datadetectortypes

IGAPP-124: Disable data detection in iOS webview

---

native/e2e/config/configs.js

Most of the time the ios e2e tests timed out. After looking at the appium logs of the failed tests you could see the error message `Capability 'waitForQuiescence' changed from string to boolean. This may cause unexpected behavior`. After some search I also found that this capability can lead to very slow or even stuck tests (more details [here](https://github.com/appium/appium-xcuitest-driver#desired-capabilities)). I don't think there is a good way to test whether the tests will work more stable after this change though. :)

IGAPP-194: Stabilize e2e tests

---

native/e2e/config/configs.js

See discussion here: https://chat.tuerantuer.org/digitalfabrik/pl/e7nedbz6g3869m376e9n3t86tr
I also tried the version 1.18.0 and 1.19.1 but both seemed worse performance wise, as they both seemed to depend on some cached files on the device. Somthing that somehow still throws me off is [this build](https://app.circleci.com/pipelines/github/Integreat/integreat-app/965/workflows/bec0546d-bfbb-4438-a429-d78e555d6daa/jobs/5219) where an unexpected timeout occurs. Besides that the native build failed I cannot see any reason why there would be a timout …

IGAPP-194: Update Version of iOS in E2E test

---

native/android/build.gradle

Changed minSDK to 21. Tested on Android 5.0, 6.0, 7.0, 8.0, 9 and 10.

IGAPP-454: App crashing because of wrong minSDK

---

.circleci/config.yml
.circleci/src/jobs/build_android.yml
native/android/app/build.gradle
native/android/fastlane/Fastfile
native/android/fastlane/README.md

5GB <= 2GB Gradle + 1GB dex + 2-2.5GB RN <= 5.5GB

IGAPP-557: Android builds failing with exit value 137

---

translations/src/config.js

Testable here: https://webnext.malteapp.de/nrw/sq tested all "specific" albanian letters (https://en.wikipedia.org/wiki/Albanian_language#Orthography) here https://fonts.google.com/specimen/Open+Sans?preview.text_type=custom#standard-styles, seems like open sans supports all letters.

IGAPP-548: Add albanian

---

CODEOWNERS

As I currently have no time for reviewing all the numerous, fancy PRs you open, I don't need to be notified by GitHub about them.
I guess this is the only reasonable way to deactivate them, right?

Remove @schedulaar from codeowners

---

e2e-tests/native/capabilities.ts
e2e-tests/native/wdio-browserstack.conf.ts
e2e-tests/native/wdio.conf.ts
e2e-tests/web/wdio.conf.ts

As always this one cannot guarante, that there will be no more failing tests. But I ran both the ios and the android tests quite often to ensure that they do not time out in 1 of 5 runs, which is about 90% better what we currently have. As I just said increasing the timeout seems to be the most sufficient solution here, as I did try a few other things, too.

IGAPP-757: Increase connectionRetryTimeout in E2E Tests

---

.circleci/config.yml
.circleci/src/jobs/check.yml
api-client/src/Endpoint.ts
api-client/src/__tests__/Endpoint.spec.ts
api-client/src/__tests__/request.spec.ts
api-client/src/endpoints/__tests__/createTrackingEndpoint.spec.ts
api-client/src/endpoints/createTrackingEndpoint.ts
api-client/src/errors/FetchError.ts
api-client/src/errors/ResponseError.ts
api-client/src/request.ts
native/src/Navigator.tsx
native/src/constants/webview.ts
native/src/routes/ExternalOffer.tsx
native/src/utils/__tests__/sendTrackingSignal.spec.ts
web/src/components/MapPopup.tsx
web/src/components/__tests__/FailureSwitcher.spec.tsx

~~This PR probably does not fix anything and is rather meant to gather additional information. This bug should not be critical as I tried and afaics all errors logged are caught and handled correctly.~~
~~The error that the `languages.json does not exist` always occurs after another error during fetching, most of the time after the following error: `Failed to load the request for the languages endpoint. Body not allowed for GET or HEAD requests` (I also found [one occurrence](https://sentry.tuerantuer.org/organizations/digitalfabrik/issues/264/events …

IGAPP-809: Languages json not existing

---

native/src/utils/renderHtml.ts
release-notes/unreleased/IGAPP-839-Fix-Paragraph-Overflow-Native.yml

Go to Kreis Höxter -> Asyl und Migration -> Information zum Asylverfahren
Switch language to FA
Text should be displayed correctly on ios & android (it was buggy on both systems!)
Tested on android emulator, ios native & emulator

IGAPP-839: Fixed missing overflow for p-tags in webview

---

tools/create-jira-release

IGAPP-826: Second release fails

---

native/src/utils/__tests__/openExternalUrl.spec.ts
native/src/utils/openExternalUrl.ts
release-notes/unreleased/IGAPP-965-inappbrowser-already-opened-error.yml

Issue is really hard and random to reproduce. Couldn't reproduce after the fix. But i'm not 100% sure if it does the trick
Open IOS Emulator/ Device
1. GoTo Testumgebung --> Corona-Virus -> Information zum Corona Virus
2. open link --> swipe from left to right
3. open next link

IGAPP-965: Ensure that inAppBrowser was closed before

---

web/src/utils/getNavigationDeepLinks.ts

1. Go to POIS and select a poi
2. click on open external link
3. if GMaps is installed the app gonna be open
4. if GMaps is not installed GMaps is opened in the browser

IGAPP-990: Open external map link opens directly apple maps on ios

---

api-client/src/__tests__/replaceLinks.spec.ts
api-client/src/replaceLinks.ts

Tested here https://regex101.com/r/ZfeAMj/1
If we also don't want to allow trailing , . / @ ... it is enough to set \b at the end of the regex. Opinions?
I also split the regex for a better overview. If you disagree with splitting it I can combine it again and keep the split part as a comment.

IGAPP-941: split regex and don't allow . at the end of the string

---

release-notes/unreleased/IGAPP-1005-double-separation-line-poi-list-bas.yml
web/src/components/PoiListItem.tsx

IGAPP-1005: Removed double separation line in location list view mobile

---

native/package.json
native/src/index.tsx
yarn.lock

IGAPP-1051: Add react-native-url-polyfill to fix broken poi urls

---

release-notes/unreleased/IGAPP-1112-parent-breadcrumb-cut.yml
web/src/components/Breadcrumb.tsx
web/src/components/Breadcrumbs.tsx

Open in mobile mode
http://localhost:9000/stadtdachau/de/allgemeine-beratungsstellen-und-beh%C3%B6rden/behoerden/jobcenter-dachau
Now all last breadcrumb items will not be cut until they reach 20 chars

IGAPP-1112: Parent breadcrumb cut

---

api-client/src/endpoints/createEventsEndpoint.ts
release-notes/unreleased/IGAPP-1107-event-order.yml

Happens for me for example for all occurrences of `Frauengruppe` and `Frauen lernen Bildungs- und Erziehungseinrichtungen kennen` in `/muenchen/de/events` using the test cms (native: Frauengruppe before Frauen lernen..., web: the other way round). I think even if this is not reproducible on all platforms (e.g. @f1sh1918 failed to reproduce it) it makes sense to have a deterministic sorting for the case that start dates are equal.

IGAPP-1107: Sort events if start dates equal

---

native/package.json
yarn.lock

IGAPP-1151: Fix android build failure by upgrading react-native

---

native/src/components/PoiListItem.tsx
release-notes/unreleased/IGAPP-920-poi-thumbnail-full-space.yml
web/src/components/PoiListItem.tsx

Show thumbnail images in 1:1 aspect ratio, even the image has a different aspect ratio

IGAPP-920: Poi thumbnail full space

---

native/android/build.gradle

**Fixes app crashing in ci. Could reproduce & fix this error locally with this change.**

IGAPP-1207: Explicitly specify kotlin version

---

api-client/src/models/PoiModel.ts
release-notes/unreleased/IGAPP-1209-app-crashes-opening-hours.yaml

- Added explicit moment locale import to fix minified import error
Reference: https://github.com/moment/moment/issues/5789
**Note:** can only be tested with release apk since error is only occurring when minifying js with hermes
(Enabling "JS Minify" in Dev Settings did not work for me to reproduce the error)
`cd android`
`./gradlew assembleRelease`
or [releaseApk](https://output.circle-artifacts.com/output/job/6732a316-7f57-4fb5-bb81-07589e139004/artifacts/0/native/android/integreat-e2e.apk)
Go to map -> click on a poi list item with OpeningHours f.e."Olympiastadion"

IGAPP-1209: App crashes openingHours

---

native/src/contexts/AppContextProvider.tsx
release-notes/unreleased/IGAPP-1214-app-crashes-with-no-city-code.yaml

Since Aschaffenburg has no location selected because it's fixed to 'hallo' (cityCode) we have to provide it in AppContext (Refactoring issue)
**Testing**
- Build and Start Aschaffenburg App
- City "hallo Aschaffenburg" should be preselected

IGAPP-1214: App crashes with no city context

---

.circleci/config.yml
.circleci/src/jobs/e2e_web.yml
docs/e2e-tests.md
e2e-tests/tsconfig.json
e2e-tests/web/waitForLocalhost.ts
e2e-tests/web/wdio.conf.ts
web/package.json

IGAPP-1227: dynamically wait for localhost in e2e tests

---

native/src/routes/CategoriesContainer.tsx
native/src/utils/DatabaseConnector.ts
release-notes/unreleased/IGAPP-1223-invalidate-city-content-cache.yml

This issue comes up due to invalidate caches for pois, due to changing structure in `DataConnector`
Therefore i added a invalidateCache fkt on refresh if this error occurs on category page.
The handling with invalid cache should be improved and maybe be invalidated in specific intervals like updating major versions.
[IGAPP-1231](https://issues.tuerantuer.org/browse/IGAPP-1231)
1. Checkout this revision: d8470389 (2023.1.5)
2. deploy on device
3. Open location f.e. Dortmund with PoiData (even Map Feature is disabled)
4. Checkout this branch
5. There should come unknown error on start
6. Click try again. Content should load (even with console.errors only occur in debug mode)

IGAPP-1223-invalidate-city-content-cache

---

e2e-tests/native/test/helpers/Gestures.ts

Somehow swiping now takes longer (?) on ios, so increasing the timeouts will fix failing builds. (Tested already in browserstack)

IGAPP-XXX: increase swipe timeout

---

.circleci/config.yml
.circleci/src/jobs/build_ios.yml

IGAPP-1270: Deprecated ios resources ci

---

api-client/src/endpoints/createEventsEndpoint.ts
release-notes/unreleased/IGAPP-1272-fix-recurring-end-dates.yml

This pull request belongs to the issue https://issues.tuerantuer.org/browse/IGAPP-1272
To test: go to http://localhost:9000/testumgebung/de/events/test-event-for-date$2023-05-15 and see that the end date is two days after the start date, not two days before.

IGAPP-1272: Fix recurring end dates

---

api-client/src/maps/index.ts
release-notes/unreleased/IGAPP-1230-map-unscrollable.yml
web/src/components/MapView.tsx

When many pois are placed at the same location and the user scrolls very close, `react-maps-gl` facing an rendering issue which is still not solved.
I think restricting `maxZoom: 21` should be fine since no one needs to zoom closer

IGAPP-1230: Map unscrollable

---

native/src/utils/__tests__/openExternalUrl.spec.ts
native/src/utils/openExternalUrl.ts
release-notes/unreleased/IGAPP-1294-internal-links-broken-ios.yml

fix opening internal links (which are handled by opening in the browser) by encoding the url

IGAPP-1294: Internal links broken ios

---

native/src/components/Categories.tsx
native/src/components/SimpleImage.tsx
release-notes/unreleased/IGAPP-1301-missing-tiles-after-installing-new-version.yml

This fix resolves the issue that the image can't be loaded from cache for ios
Testing:
- Checkout revision: a0b47588
- deploy on ios
- choose a city
- checkout this branch
- deploy on ios
- select same city as on the other branch
- tiles should load as expected
Tested on ios simulator and real device

IGAPP-1301: Missing tiles after installing new version

---

native/src/components/SimpleImage.tsx
release-notes/unreleased/IGAPP-1308-remove-ios-image-caching.yml

I removed the cache control `reload` since its not needed in our case and was used to fix a bug with local images on ios which were not working and was already fixed. So we can fallback to default caching strategy.
You can find more information here
https://reactnative.dev/docs/images#cache-control-ios-only

IGAPP-1308: Remove ios image caching

---

native/src/components/OrganizationContentInfo.tsx
native/src/components/TextLink.tsx

@steffenkleinle I couldn't get the styling to work with the existing Touchable link but this did the trick. What do you think?

IGAPP-1191: Add a TextLink

---

native/src/utils/DataContainer.ts
native/src/utils/DatabaseConnector.ts
native/src/utils/FetcherModule.ts
native/src/utils/__tests__/DatabaseConnector.spec.ts
native/src/utils/__tests__/DefaultDataContainer.spec.ts
native/src/utils/loadResourceCache.ts

Remove the unused property lastUpdate of fetch results which was sometimes undefined and therefore crashing the app.
- Unused property lastUpdate sometimes returned by NativeFetcherModule is now ignored
- Unused property lastUpdate of resource cache was removed and is not saved to database connector anymore
- Removing the property and not paring it as DateTime avoids the app crashing
- There is no more lastUpdate timestamp for resource cache entries
Fixes: #2314 
---

2314: Remove unused and sometimes missing lastUpdate property

---

release-notes/ReleaseNoteTemplate.yml

The template for the release notes now mentions a Github issue number instead of a JIRA issue key.
---

Update template for release note

---

native/src/components/PoiFiltersModal.tsx
native/src/routes/Pois.tsx
release-notes/unreleased/2377-poi-category-others.yml

This PR fixes the selection of the `Other` category in the poi filters.
- Use correct check instead of `===`
Fixes: #2377
---

2377: Fix other category

---

api-client/jest.setup.ts
native/jest.setup.ts
translations/jest.setup.ts
web/jest.setup.ts
web/src/utils/sentry.ts

Disabled console.error in jest tests
Changed default console.error behavior
Fixes #2407

Disable console.error in tests #2407

---

release-notes/unreleased/2409-improve-poi-category-filter-layout.yml
web/src/components/ModalContent.tsx
web/src/components/PoiFilters.tsx
web/src/components/PoisDesktop.tsx
web/src/components/base/ToggleButton.tsx
web/src/constants/dimensions.ts
web/src/routes/PoisPage.tsx

Depending on the amount of categories the filter layout of the toggle buttons look weird/displaced
The amount of icons per row is now depending on the width of the panel and implemented with a grid layout
Items of the next should should align left.
Hopefully none
#2409 
Desktop Panel
mobile
iPadMini (768px width before it breaks to desktop)

2409: Improve poi category filter layout

---

release-notes/unreleased/2381-tabbing-kebab-menu.yml
web/src/components/KebabMenu.tsx

When tabbing all the way through the app, at the very end it would open the kebab menu because it was already there just visibly hidden and the tab somehow seems to trigger an `onClick` there. This also tells the HTML that the menu is hidden when the user can't see it, and now doesn't open just by tabbing through anymore.
Fixes: #2381 
---

2381: Don't open the kebab menu when tabbing through the app

---

native/jest.setup.ts
native/src/Navigator.tsx
native/src/__tests__/Navigator.spec.tsx
native/src/components/__tests__/NearbyCities.spec.tsx
native/src/contexts/AppContextProvider.tsx
native/src/utils/PushNotificationsManager.ts
native/src/utils/__tests__/PushNotificationsManager.spec.ts
native/src/utils/__tests__/createSettingsSections.spec.ts
native/src/utils/createSettingsSections.ts
release-notes/unreleased/2438-fix-push-news-android-13.yml

Since Android 13 explicit push notification permission has to be requested, which will be done with this PR.
- Check on app start whether permissions are already available and request them and subscribe to channel otherwise (on android 13+)
- Decouple subscribing to channel from permissions on city/language change
- Use react-native-permissions to ask for permissions
- Permissions are not requested anymore if changing city/language.
Fixes: #2438.
---

2438: Fix push notifications for android 13+

---

api-client/src/models/DateModel.ts
api-client/src/models/__tests__/DateModel.spec.ts
release-notes/unreleased/2496-wrong-dst.yml

Our rrule doesn't support working with timezones, therefore the time was wrong if the start dates was in DST and the some recurrences not or the other way round. This PR also adds the offset such that times are displayed correctly.
Keep the offset of the original start date and add the offset difference to all dates returned by rrule.
None.
Fixes: #2496.
---

2496: Dates of recurring events wrong if changing to daylight saving time

---

README.md

Pre-commit has been fixed and there is no longer need to mention it on Readme
Fixes: #2514
---

2514: Remove pre-commit from Readme

---

native/ios/fastlane/Fastfile

Removing a signature that is copied twice by XCode 15.
Because the thought has crossed my mind to not: We need XCode 15 for the latest rn-permissions, which we in turn need to keep the calendar exports working for iOS 17.
Fixes: #2554

2554: Add workaround for XCode 15

---

native/ios/Integreat.xcodeproj/project.pbxproj
native/ios/fastlane/Fastfile

Mapbox has some issues with certificate duplicates on ios with Xcode 15 builds.
-  add a script that removes the old certificate in the build phase for XCode15
Fixes: #2556 
Here is a pipeline log for the branch (build ios):
https://app.circleci.com/pipelines/github/digitalfabrik/integreat-app/9992/workflows/effc5556-e2f7-4a66-9f08-9e2c79fc515d/jobs/55885
Further information:
https://github.com/CocoaPods/CocoaPods/issues/12022

Fix-XCode15-bug

---

release-notes/unreleased/2575-focus-trap-bottom-action-sheet.yml
web/src/components/Modal.tsx

Focus trap lib since `10.x` can not detect nodes from a portal (bottom action sheet) and will throw an error (opening feedback modal)
- added a legacy displayCheck for finding the node in the portal
Fixes: #2575 
---

2575: Focus trap bottom action sheet

---

web/src/components/SearchInput.tsx

Short description
The Search Icon is not centered with the input "Suche"
Proposed changes
Center and align the Search Icon with the input, set it a little lower
Side effects
Resolved issues
The Search Icon is aligned with the Input "Suche"
Fixes: https://github.com/digitalfabrik/integreat-app/issues/2580
---

2580: Center search icon

---

docs/e2e-tests.md
e2e-tests/native/wdio-ios.conf.ts
e2e-tests/package.json
native/docs/e2e-testing.md
yarn.lock

This updates the documentation for running the e2e tests locally.
I only added how to add env variables in zshell because it's the default shell on Mac but maybe someone with a Windows machine can add their version.
Fixes: #2523 
---

2523: Update documentation for e2e tests

---

native/ios/Integreat/Info.plist

These purpose strings are just fallbacks for avoiding messages from apple of missing purpose strings. They shouldn't be used in the app but the localized purpose strings
Please switch your ios device language to something thats not english and test if the correct localized strings will still be used
- add fallbacks to the info.plist in english
Fixes: #2607 
---

2607: Missing purpose strings 

---

web/package.json
yarn.lock

Upgrade ReactStickyHeadroom dependency to v2
ReactStickyHeadroom powers the header of the web app. No changes should be visible.

Upgrade Headroom to v2

---

native/src/components/__tests__/DatesPageDetail.spec.tsx
release-notes/unreleased/2647-next-recurrence.yml
shared/api/models/DateModel.ts
shared/api/models/__tests__/DateModel.spec.ts
web/src/components/__tests__/DatesPageDetail.spec.tsx

Fix the displaying of the next recurrence of events if its near.
- Substract timezone offset difference from dates passed to rrule to account for usage of "local time" 
- Substract duration from dates passed to rrule to include currently happening events
None.
Fixes: #2647.
---

2647: Fix next recurrence of events

---

release-notes/unreleased/2652-breadcrumbs-not-only-list-items.yml
web/src/components/Breadcrumbs.tsx

For a11y purposes all children of an ordered or unordered list should be `<li>`
- wrap home icon into `<li>`
Fixes: #2652
---

2652: Breadcrumbs not only list items

---

native/src/components/PoiDetails.tsx
release-notes/unreleased/2695-fix-ig-cities-available-in-halloaschaffenburg.yml
web/src/CityContentSwitcher.tsx
web/src/FixedCityContentSwitcher.tsx
web/src/RootSwitcher.tsx
web/src/__tests__/CityContentSwitcher.spec.tsx
web/src/__tests__/FixedCityContentSwitcher.spec.tsx
web/src/components/PoiDetails.tsx

Currently it is possible to open IG cities in Aschaffenburg, when directly navigating to the url 
-> https://halloaschaffenburg.de/kreis-bergstrasse/de
This should be avoided, by not loading any other city than the fixed city.
- Add a fixedCityContentSwitcher, which checks whether the params `cityCode` is the `fixedCity`
Fixes: #2659

2659: Don't load other cities when fixed city is set

---

translations/translations.json

Add purpose strings for calendar permissions, use Sie for malte help form and add translations.
None.
Partly fixes: #2608.
---

2608: Add purpose strings for calendar permissions, use Sie for malte help form and add translations

---

release-notes/2024.2.5/2677-share-link-not-clickable.yml
web/src/components/SharingPopup.tsx
web/src/components/__tests__/SharingPopup.spec.tsx

When a user wants to share a page f.e. via mail the link is not clickable due to missing whitespace
- add a whitespace
Fixes: #2677
---

2677: Share link not clickable

---

build-configs/BuildConfigType.ts
build-configs/aschaffenburg/index.ts
build-configs/integreat/index.ts
build-configs/malte/index.ts
build-configs/obdach/index.ts
native/src/constants/__mocks__/buildConfig.ts
web/tools/webpack.config.ts

To avoid the lookalike phishing warning I added integreat.app and integreat-app.de to assetlinks.json file.
- add build config property allowed lookalikes
- set lookalikes in .well-known/assetlinks.json
Fixes: #2475
---

2475: Add list of allowed lookalikes to config & assetlinks.json

---

native/src/routes/SearchModal.tsx
release-notes/unreleased/2727-search-result-pois-events-missing.yml
shared/hooks/useSearch.ts
version.json
web/src/hooks/useAllPossibleSearchResults.ts

Currently for async search not all search results were found with `minisearch`. The issue is that the indexing was not ready when the query was typed and missing results were not reloaded.
- reload search results when indexing has finished
- during typing search query the search results change but if we want it async/non blocking, i think we can't find a better solution
Fixes: #2727
- Go to a location
- open the search and type in immediately your search query. All results should be shown

2727: Search result pois events missing

---

native/src/components/Categories.tsx
native/src/components/CategoryListItem.tsx
native/src/components/NavigationTile.tsx
native/src/components/NavigationTiles.tsx
native/src/components/PoiDetails.tsx
native/src/components/PoiListItem.tsx
native/src/components/SearchListItem.tsx
native/src/components/SimpleImage.tsx
native/src/components/SubCategoryListItem.tsx
native/src/components/Tile.tsx
native/src/components/Tiles.tsx
native/src/components/__tests__/SearchListItem.spec.tsx
native/src/models/TileModel.ts
native/src/routes/Offers.tsx
native/src/utils/DatabaseConnector.ts
native/src/utils/ResourceURLFinder.ts
native/src/utils/__tests__/getCachedThumbnail.spec.ts
native/src/utils/getCachedThumbnail.ts
shared/api/models/CategoryModel.ts
shared/api/models/EventModel.ts
shared/api/models/ExtendedPageModel.ts
shared/api/models/PoiModel.ts
shared/api/types.ts
shared/hooks/useSearch.ts
web/src/components/Page.tsx
web/src/components/PoiDetails.tsx
web/src/components/SearchListItem.tsx
web/src/components/Tile.tsx
web/src/models/TileModel.ts
web/src/routes/EventsPage.tsx

Use correct thumbnails for pois and fix thumbnail type.
- Remove unnecessary `.replace('150x150', '')` for poi thumbnails
- Make thumbnail type optional for categories, events and pois to match api
- Refactor `SimpleImage` to support local svg icons
- Refactor `NavigationTile`
Hopefully none.
Fixes: #2635.
---

2635: Use correct thumbnails

---

native/src/utils/DatabaseConnector.ts
release-notes/unreleased/2747-wrong-times.yml
shared/api/models/DateModel.ts
shared/api/models/EventModel.ts
shared/api/models/__tests__/DateModel.spec.ts

Fix wrong event times by calculating offset difference from current date.
- Always store the start date from the CMS
- Only access start and end date of recurrences
- Invalidate offline content
The current problem was that we set the first recurrence as start date with an adjusted offset calculated from the start date. This adjusted start date is saved to the offline content. Next time we load a start date with already adjusted offset and adjust the offset again leading to wrong times.
The offline content will be deleted.
Fixes: #2747.
---

2747: Fix wrong event times

---

build-configs/BuildConfigType.ts
build-configs/integreat/index.ts
release-notes/unreleased/2674-add-accessibility-to-footer.yml
translations/translations.json
web/src/components/CityContentFooter.tsx
web/src/components/GeneralFooter.tsx

Adding the accessibility declaration to the footer for Integreat.
- Adding the accessibility declaration to the build config for Integreat. We probably need a separate one for Aschaffenburg at some point, and Malte doesn't need one.
Fixes: #2674 
---

2674: Add accessibility declaration to the footer

---

.circleci/config.yml
.circleci/src/commands/restore_ruby_cache.yml
.circleci/src/jobs/e2e_android.yml
.circleci/src/jobs/e2e_ios.yml

Fix execution of e2e tests in CI by using image including ruby and ruby bundler.
In #2772 I upgraded/changed the used images in the e2e-android and e2e-ios jobs to just plain node ones (before it was cimg/android). Since neither are the right choice (android including unnecessary stuff and being confusing, node not including ruby and ruby bundler), I changed the used images to cimg/ruby. 
None.
Fixes: None.
---

2739: Fix e2e tests

---

native/src/components/CategoryListItem.tsx
native/src/components/SearchListItem.tsx
native/src/components/SubCategoryListItem.tsx
release-notes/unreleased/2767-cut-off-text.yml

Fix cut off texts in category list. Both #2769 and #2771 did not work for me/broke some other styling. This PR should resolve all those problems with minimal changes.
- Remove unused thumbnail for SubCategoryListItem
- Set `flex-shrink: 1` on `CategoryListTitle` to fix wrapping
None.
Fixes: #2767.
---

2767: Fix cut off texts in category list

---

native/Gemfile

Fix failing iOS delivery.
Add gem `rb-readline` to fix error during delivery on macos image.
None.
Fixes: None.
---

2588: Fix failing iOS delivery

---

web/src/components/Header.tsx

Remove the shadow in the header on mobile (web).
Remove shadow and padding for header and first children on mobile web.
Less padding between the icons (but imo not needed).
Fixes: #2801.
---

2801: Remove shadow in header on mobile

---

web/src/index.ejs

In https://github.com/digitalfabrik/integreat-cms/pull/2391, I suggested to return a partial HTML response to be able to localize the `lang` attribute of the root `html`tag, e.g.:
```
<html lang="de-DE">
<head>
<title>Willkommen - Augsburg | Integreat</title>
<meta name="apple-mobile-web-app-title" content="Willkommen - Augsburg | Integreat">
<meta name="twitter:title " content="Willkommen - Augsburg | Integreat">
<meta name="twitter:card" content="summary">
<meta property="og:title" content="Willkommen - Augsburg | Integreat">
<meta property="og:description" content="Willkommen in Augsburg">
<meta name="twitter:description" content="Willkommen in Augsburg">
<meta property="og:image" content="http://localhost:8000/static/logos/integreat/social-media-preview.png" />
<meta …
```

Make nginx server side includes compatible with CMS

---

web/src/routes/EventsPage.tsx

Implemented dynamic padding for page details `Spacing` component
- Added `content` and `lastUpdate` props to `Spacing` component
- `Spacing` now renders padding based on props above
None.
Fixes: #2686.
PR to merge #2816.
---

2686: Implement dynamic padding bottom for page details

---

native/ios/Integreat/fetcher/FetchResultCollector.swift

In the iOS emulator, particularly when in Testumgebung, I keep getting lots of the console warning "Sending 'progress' with no listeners registered". This is pretty annoying when trying to use the console for debugging.
According to https://reactnative.dev/docs/native-modules-ios#sending-events-to-javascript, we shouldn't be emitting events at all if no listeners for those events are registered, so I followed that advice.

Fix annoying iOS 'progress' listener warning

---

native/src/components/Modal.tsx
native/src/components/PoiFiltersModal.tsx
release-notes/unreleased/2856-POI-filter-is-too-long-for-display.yml

The POI filter on 5,5" phone leads two categories to be cut and it's not possible to scroll.
~- Used FlatList instead of .map() for build-in scrolling.~
~- Defined numbers of numColumns 3 to make it consistent on all devices~
~- Computed the flatListHeight dynamically from poiCategories length divided by numOfColumns to get number of rows multiplied by toggleButtonHeight.~
~- Used a ScrollView that wraps around opening hours section and categories section.~
- Fixed an issue with the scrollView at the modal where I replaced `{flex:1}` with `{flexGrow: 1}`
Tested on virtual devices with the following screen: 5.0, 5.5, 6.7 inches.
None.
~Note: I disabled scrollView from Modal (scrollView={false}) because VirtualizedLists doesn't like to be nested in ScrollViews.~ …

2856: poi filter is too long for display and no scrolling available

---

release-notes/unreleased/2880-Repeating-dates.yml
shared/api/models/DateModel.ts
shared/api/models/__tests__/DateModel.spec.ts

The repeating dates were off again. Reminder, the underlying problem is that the package `rrule` handles time zones by ignoring them and pretending that everything is in UTC. This time, we had the problem that e.g. all-day events arrive with a starting time of 0:00+2 which translates to 22:00 on the previous day in UTC. If we then go and get for example the next Saturday from that, we get Saturday at 22:00 in UTC, which translates to midnight on Sunday in local time.
Links for testing: http://localhost:9000/testumgebung/de/events/jeden-donnerstag and https://cms-test.integreat-app.de/testumgebung/events/de/4596/edit/
Note: I haven't found a well-supported alternative package, but man, would I be happy to switch.
- Move the start date in the recurrence rule to local time, then get the next …

2880: Fix repeating dates. Again.

---

shared/utils/normalizePath.ts

Prevent app from crashing for invalid urls.
- Catch errors in `normalizePath` and return the NOT_FOUND route to show an error (which will lead to a not found error being displayed)
- Do nothing if the server already returns an error (the second case in the issue)
None.
This can't be tested with webpack-dev-server. We have to release this to webnext and then test there.
To simulate the behavior, you can change [L53 in `CityContentSwitcher`](https://github.com/digitalfabrik/integreat-app/blob/34857b4c87f3d07e764fd05fd4c05fb6188a8ddc/web/src/CityContentSwitcher.tsx#L53) to
``` ts
const pathname = normalizePath('/lkmuenchen/ru/%D0%BF%D1%80%D0%B8%D0%B1%D1%8B%D1%82%D0%B8%D0%B5-%D0%B8-%D0%B6%D0%B8%D0%B7%D0%BD%D1%8C-%D0%B2-%D0%B3%D0%B5%D1%80%D0%BC%D0%B0%D0%BD%D0%B8%D0%B8/%D0%BC%D0%BE%D0%B1%D0%B8%D …
```

2922: Prevent app from crashing for invalid urls

---

release-notes/unreleased/2948-unique-chat-id.yml
web/src/components/ChatController.tsx

Start a new chat for each region instead of sharing the chat instance.
This would break the chat in the backend.
Store the id of the chat in the local storage related to the city.
:warning: Previous chats won't work anymore (unless the chat id is copied manually to the new local storage entry).
Open the chat in testumgebung and send a message.
Then go to muenchen and open the chat and confirm that there is no chat yet.
Fixes: #2948, https://github.com/digitalfabrik/integreat-chat/issues/54.
---

2948: Start a new chat for each region

---

native/package.json
native/src/__tests__/Navigator.spec.tsx
native/src/components/Page.tsx
native/src/components/RemoteContent.tsx
native/src/components/__tests__/CategoryListItem.spec.tsx
native/src/components/__tests__/SearchListItem.spec.tsx
native/src/constants/webview.ts
native/src/routes/__tests__/SearchModal.spec.tsx
release-notes/unreleased/2160-jumping-webview.yml
yarn.lock

This PR fixes both #2160 and #2886 caused by the webview jumping on simple press on Android.
- Switch to https://github.com/birdofpreyru/react-native-webview (a well-maintained fork of https://github.com/react-native-webview/react-native-webview) that fixes the upstream issue https://github.com/react-native-webview/react-native-webview/issues/3014
- We might switch back to the original library once the issue is fixed upstream
None.
Test if this PR resolves the two linked issues and try clicking various elements in our content.
Fixes: #2160, #2886.
---

2160: Fix jumping webview issue by switching libraries

---

native/package.json
yarn.lock

Fix app crash for scaleX on svg.
Upgrade react-native-svg.
None.
See issue.
Fixes: #2961.
---

2961: Fix app crash for scaleX on svg

---

e2e-tests/shared/constants.ts
shared/api/models/__tests__/EventModel.spec.ts

- Rename e2e testumgebung
- Fix failing unit test by mocking time
None.
Fixes: #2924.
---

2924: Rename e2e testumgebung

---

.circleci/config.yml
.circleci/src/jobs/build_android.yml
.circleci/src/jobs/deliver_android.yml
native/android/fastlane/Fastfile
native/fastlane/Fastfile
version.json

Switch to android app bundles (.aab) to reduce download size.
- Build and upload .aabs
- Continue to include .apks to the release notes
- None.
None.
Fixes: #2953
---

2953: Switch to android app bundles (.aab)

---

native/run

Speed up local development android builds using `--active-arch-only` flag.
See https://reactnative.dev/docs/build-speed#build-only-one-abi-during-development-android-only.
Android build  still works.
Fixes: None.
---

Speed up local development android builds

---

release-notes/unreleased/2924-security-error.yml
web/src/hooks/__tests__/useLocalStorage.spec.tsx
web/src/hooks/useLocalStorage.ts

Catch SecurityError when accessing localStorage and prevent app from crashing.
- Wrap access of localStorage in a try/catch block
None.
I did not find a way to test this locally (as in: using a development server on localhost) due to me being unable to block localhost from accessing the local storage. Let me know if you can think of another way.
Fixes: #2924
---

2924: Catch SecurityError when accessing localStorage

---

native/src/components/MapView.tsx
native/src/components/base/IconButton.tsx
native/src/hooks/useUserLocation.ts

Fix map user location with approximate permission (for degoogled devices only?).
- Initialize the map user location with the result of `refreshPermissionAndLocation`
- None?
Same as in #2980.
Partly fixes: #2949.
---

2949: Fix map user location with approximate permission

---

native/src/components/Header.tsx

I created an error via typecasting that didn't take the possibility of an undefined into account, in https://github.com/digitalfabrik/integreat-app/pull/2910 . This fixes it.
- Change typecasting to also allow undefined
- None
See if you can open all pages in the app, particularly settings.
Fixes: #2996 
---

2996: Fix settings

---

web/src/components/CityContentToolbar.tsx
web/src/components/Feedback.tsx
web/src/components/FeedbackContainer.tsx
web/src/components/FeedbackToolbarItem.tsx
web/src/components/Layout.tsx
web/src/components/SearchFeedback.tsx
web/src/components/__tests__/FeedbackContainer.spec.tsx
web/src/components/__tests__/FeedbackToolbarItem.spec.tsx
web/src/styles/Aside.css

The municipalities have been receiving way less feedback since we made some changes there about half a year ago. In this PR, I changed the sidebar in web desktop / the footer in web mobile to show the two smileys instead of the button saying Feedback.
- Instead of showing the FeedbackIcon in the sidebar / footer, this shows the HappySmileyIcon and the SadSmileyIcon
- A click on either of those icons opens the feedback overlay with the clicked icon selected
- I added a Portal around the sidebar in web desktop to avoid the sidebar poking through when the language selection screen is open
- If the device is narrower than 408px, the sad smiley jumps to a new row. Do we have a minimum width that we support?
- Check that sending feedback still works
- Check that the sidebar isn't hidden behind …

2548: Split up web feedback at the first level into two smileys again

---

.circleci/config.yml
.circleci/src/commands/unit_test.yml
.circleci/src/workflows/commit.yml
.circleci/src/workflows/delivery.yml
.circleci/src/workflows/native_beta_delivery.yml
.circleci/src/workflows/native_production_delivery.yml
.circleci/src/workflows/web_beta_delivery.yml
.circleci/src/workflows/web_production_delivery.yml
README.md

Remove codeclimate from CI to fix builds of forks. Codeclimate was not actively used by us anymore.
- Remove codeclimate
- The corresponding context in circleci can only be removed after this is merged to avoid failing builds
Just have a look at the builds and see that they succeed.
Fixes: #2818
---

2818: Remove codeclimate from CI to fix builds of forks

---

web/src/components/Layout.tsx

We currently have the beautiful line `width: ${props => (props.$fullWidth ? '100%' : dimensions.maxWidth - 2 * dimensions.toolbarWidth)}px;` in our code which leads to the `width: 100%px;` when `$fullWidth` is `true`. Until merging #3004, that was not a problem (I assume it was overwritten somewhere but I honestly don't see it). After merging #3004, we have a slight layout issue here: https://webnext.integreat.app/augsburg/en/locations This PR fixes that.
- Puts the `px` where it belongs
- Updates the `max-width` to account for the `$fullWidth` prop
- I hope no new ones!
Look at http://localhost:9000/testumgebung/de/locations in a desktop browser, compare it to https://webnext.integreat.app/augsburg/en/locations.

Hotfix: Fix map layout

---

web/src/routes/SearchPage.tsx

When the search page opens, it shouldn't show a loader while we're loading stuff that the user can't see.
- Show only the search bar when the query is empty.
- Should be none
Compare the loading of https://integreat.app/testumgebung/de/search and http://localhost:9000/testumgebung/de/search
Fixes: #3008 
---

3008: Hide the loader when first opening the search page

---

CODEOWNERS

Sorry, I'm not sure why my editor autocorrected the `*` to a `-` in the last PR for the codeowners but this fixes it.

Fix autocorrected typo

---

native/src/routes/CityNotCooperating.tsx

Currently the copy text is not shown fully, half of it is cut off. The text should be fully shown.
Fix the scroll view and the template text's style
none
Fixes: #2909 
---

2909: Fix copy text being cut off in the suggest your region page

---

web/src/App.tsx
web/src/components/DatePicker.tsx

Calendar button for Event's date filter has a position problem when switching to RTL language.
- Switching sides depending language direction. 
- I had to fix the language direction by getting the i18nextLng from localStorage and setting the initial value for contentLanguage state at app.tsx (becouse when refreshing the page contentLanguage gets undefined to it defaults to ltr language)
- App.tsx (web)
- DatePicker.tsx (web)
Fixes: #3048 
---

3048: Calendar button position fix

---

release-notes/unreleased/3054-fix-rtl-display-events.yml
web/src/components/ListItem.tsx

It looks like due to not needed direction tags, the rtl events are not displayed correctly,
- removed not needed direction tags for title row, since they will be inherited from `ListItemContainer`
- may affect other components that use ListItems (Licenses, Pois, Breadcrumbs)
Open: http://localhost:9000/testumgebung/ar/events
Fixes: #3054
---

3054: Fix rtl display events

---

web/src/App.tsx
web/src/components/KebabMenu.tsx
web/src/styles/KebabMenu.css

Currently the category pages are having additional scrollable blank height after the toolbar footer on the small screens if the side kebab-menu is activated. This might be happening because of the `visibility: hidden` attribute of the `Portal` potentially taking up unintended space due to it being a part of the DOM, therefore it could still occupy space.
- use display instead of visibility
- add relative position to the parent element (body), because of the child `Portal` element having the absolute position
- add z-index to be placed above the category elements
- refactor `window.scrollY`  to calculate and memoize the value and to make sure the side menu starts at the top of the screen
- Open the side-menu on the small screen and check the category and its children to see if there is …

3020: Fix unexpected scrolling behaviour in mobile desktop

---

native/src/components/Feedback.tsx
native/src/components/FeedbackContainer.tsx
native/src/components/__tests__/Feedback.spec.tsx
native/src/components/__tests__/FeedbackContainer.spec.tsx
native/src/routes/__tests__/SearchModal.spec.tsx
translations/translations.json
web/src/components/SearchFeedback.tsx
web/src/routes/__tests__/SearchPage.spec.tsx

This is the implementation of the redesign of the search feedback in native.
- When there are no search results, the text makes it clearer that we also searched in the fallback language, and a suggestion to try a different language.
- When there are no search results, there is a very clear CTA to open the feedback form if the user thinks there is information missing anyway.
- The design also calls for the number of search results to disappear if there aren't any but I decided against that so that a screen reader can still yell at someone to stop typing if they already have no results (#2352)
- The sad smiley in the search feedback disappears (though I'm not sure that qualifies as a side effect since that's the design)
- I used German as the hard-coded fallback language in the …

2926: Redesign search feedback native

---

release-notes/unreleased/3058-fix-truncated-links-in-push-notifications.yml
shared/utils/__tests__/replaceLinks.spec.ts
shared/utils/replaceLinks.ts

The underscore does not exist in regex for path which is leading for. ex. this path to pdf file `https://bildung-fuerth.de/fileadmin/media/pdf/Sprachwegweiser_2024.pdf ` being truncated in push notifications. 
- add `_` to path in regex
- none
- Go to Testumgebung http://localhost:9000/testumgebung/de/news/local/11356
- Click on the link and see that the page is not found
Fixes: #3058 
---

3058: Fix truncated path links in push notifications

---

web/src/components/ChatConversation.tsx
web/src/components/ChatMessage.tsx
web/src/components/__tests__/ChatConversation.spec.tsx

Typing indicator message (...) for 60 seconds should be shown after automatic answer in chat. It will be a temporary solution untill the websocket implementation
- Add typing indicator function
- Style typing indicator in a similar manner
- none
Fixes: #3029 
---

3029: Add typing indicator for automatic replies in chat

---

native/ios/Integreat.xcodeproj/xcshareddata/xcschemes/aschaffenburg.xcscheme
native/ios/Integreat.xcodeproj/xcshareddata/xcschemes/integreat-e2e.xcscheme
native/ios/Integreat.xcodeproj/xcshareddata/xcschemes/integreat-test-cms.xcscheme
native/ios/Integreat.xcodeproj/xcshareddata/xcschemes/integreat.xcscheme
native/ios/Integreat.xcodeproj/xcshareddata/xcschemes/malte.xcscheme

Fix iOS build scripts as xcode does not find homebew (and therefore yarn) in my path.
Otherwise I always get `yarn: command not found`.
- Add homebrew to path before executing build scripts
homebrew is always added to the path even if not available/necessary. Should not lead to any problems though.
Build the app on iOS.
Fixes: N/A
---

Fix iOS build scripts

---

native/src/routes/CategoriesContainer.tsx
native/src/routes/SearchModal.tsx
native/src/routes/SearchModalContainer.tsx
native/src/routes/__tests__/SearchModal.spec.tsx
shared/hooks/useSearch.ts
shared/index.ts
web/src/hooks/__tests__/useLoadSearchDocuments.spec.ts
web/src/hooks/useLoadSearchDocuments.ts
web/src/routes/SearchPage.tsx
web/src/routes/__tests__/SearchPage.spec.tsx

Reduce search loading times by fixing minisearch initialization and rename to documents
- Decouple initialization of minisearch and adding documents
- Avoid rerender if documents are of the same length
- Avoid returning null if not all documents indexed
- Change naming to `(search) documents`
- Search results might appear after some delay
Test search on native and web thoroughly! Test both searching in German and other languages and make sure that German search terms are also found in other languages.
Fixes: #3107
---

3107: Reduce search loading times

---

.idea/integreat-app.iml
native/.idea/integreat-app-native.iml
web/.idea/integreat-app-web.iml

Include ios and android for native and allow use of root project in IntelliJ.
This allows searching these files as well.
- Remove exclusion of ios and android on native
- Remove exclusion of native and web in the root project
- Mark directories correctly
The docs saying "open web or native" separately is kinda outdated/not the only option anymore. However, I would first try to work with the root project only for a bit before changing that recommendation.
Open the root or native project and play around. Let me know if you find this annoying.
Fixes: N/A
---

Include ios and android for native and allow use of root project in IntelliJ

---

native/src/components/TtsContainer.tsx
native/src/utils/sentry.ts

Prevent unnecessary tts stop causing errors if no tts engine installed.
- Prevent unnecessary tts stop causing errors if no tts engine installed.
- Refactor reportError
- [This error](https://sentry.tuerantuer.org/organizations/digitalfabrik/issues/1502) will not be sent to sentry anymore. We have 537k events for it, which seems more than enough. I [investigated this](#1759) in the past, but wasn't able to fix it. However, it is handled and not a problem.
- ~~I thought of preventing sending a sentry stacktrace for known issues (such as this one), but decided against as it still might be helpful to detect issues such as this one. However, we will continue to get this error for people that try to open the tts player but dont have a tts player installed.~~ Due to the unexpected behavior on …

3112: Prevent unnecessary tts stop

---

release-notes/unreleased/2925-add-array-at-polyfill.yml
web/package.json
web/src/App.tsx
yarn.lock

We have lots of issues of e.at() is not a function in sentry:
Sentry Issue: [INTEGREAT-APP-70V](https://sentry.tuerantuer.org/organizations/digitalfabrik/issues/7570/?referrer=github_integration)
- Added a well maintained library called [core-js](https://www.npmjs.com/package/core-js)
- a reddit post mentioned this issue you can find it here: [Reddit post](https://www.reddit.com/r/webdev/comments/1fno3ux/comment/looxlo8/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)
None.
- You can use https://www.browserling.com/ with windows 10 + chrome 86 without these 2 lines:
```
import 'core-js/actual/array/at'
import 'core-js/actual/string/at'
```
- You have to enable tunneling to test it through ssh.
- Without the package it will say "An unknown error …

2925: Add array at polyfill

---

native/src/components/base/InputSection.tsx

The text fields in the form inputs (feedback and Malte help form) didn't have an accessible description, now they do.
- Added `accessibilityLabel` to the inputs
- None
Use VoiceOver or iOS Accessibility Inspector or TalkBack to look at the feedback form.
Fixes: #3066 
---

3066: Add accessibilityLabel to form inputs

---

release-notes/unreleased/3074-debounce-to-search-query.yml
shared/hooks/useSearch.ts

Return the results after several milliseconds to user so that the user could have time to finish typing
- Add debounce function to `useSearch` hook
- Add timeout for 250 Milliseconds
- should be none
Search for something, for ex. "Dolmetscher"
See that the results for the query appear after 250 Milliseconds
Fixes: #3074 
---

3074: Add debounce function to query search to improve responsiveness

---

shared/utils/__tests__/pois.spec.ts
shared/utils/pois.ts

Currently categories in PoiFilters are not sorted alphabetically even though there is a text saying `Categories A-Z`
- Added sort() method
- Adjust tests so that it equals sorted items
- none
- Go to Map
- Click on `Filter locations`
- See a sidebar with categories
Fixes: #3131 
---

3131: Fix categories not in alphabetical order

---

.circleci/config.yml
.circleci/src/jobs/promote_android.yml
.circleci/src/jobs/promote_ios.yml
native/ios/fastlane/Fastfile
version.json

Fix fastlane installation for promotion.
- Run the ruby installation in the correct directory
- Fix the metadata path for ios
N/A
See that the pipeline succeeds: https://app.circleci.com/pipelines/github/digitalfabrik/integreat-app?branch=fix-promotion
Or, well, see that at least Android succeeded :D
Fixes: N/A
---

Fix fastlane installation for promotion

---

tools/github-promote-release.ts

Currently, only the latest prerelease flag of the latest github release of the current platform is removed during a promotion. Accordingly, there are quite a few releases which still have the prerelease flag set.
However, this is wrong, as also those releases (or whatever is included in those releases) is now on production.
- I filtered all Ids that are related to that platform then updateRelease for each id of these.
Note: this PR will have conflects with #3079
None
N/A
Fixes: #3088
---

3088: Remove all previous prereleases

---

web/src/components/base/Tooltip.tsx

Tooltip is being half hidden when a user hovers over `Change Language` button in big width view. 
- Set higher z-index to Tooltip
- none
Hover over `Change Language` button in web and see that the language selector container covers the half of the tooltip
Fixes: #3135 
---

3135: Fix tooltip being half hidden on language change hover

---

web/src/components/ChatController.tsx

With the [latest change of the Integreat CMS](https://github.com/digitalfabrik/integreat-cms/pull/3559) we introduced caching of Zammad responses. This makes the API quite fast and we can decrease polling times to improve the experience for the user.
- Decrease chat polling interval to 8s.
- More load on the CMS and more bandwidth usage. However, still only a few KB.
Fixes: None
---

Decrease chat polling interval

---

web/src/components/SearchInput.tsx
web/src/routes/SearchPage.tsx

Currently search term stays in input after language change but the url query gets cleared out. The query and search term input should be there after language change
- change `defaultValue` to `value` in TextInput because defaultValue contains the default value, while value contains the current value after some changes have been made. 
- use UseEffect to update filterText
- none
- Go to the search page
- Search for `Augsburg`
- Change the language
- See that url query and search input text disappear
Fixes: #3117 
---

3117: Fix search term half-stays on language change

---

native/src/routes/Consent.tsx

At External Sources page in the settings the description is touching the edges of the screen.
- Added padding to consents description
None.
- At native go to settings then External Sources.
- The description should have padding.
Fixes: #3000 
---

3000: Padding for external sources

---

build-configs/BuildConfigType.ts
build-configs/aschaffenburg/index.ts
build-configs/common/theme/colors.ts
build-configs/integreat/index.ts
build-configs/integreat/theme/colors.ts
build-configs/integreat/theme/index.ts
build-configs/malte/index.ts
build-configs/obdach/index.ts
native/src/constants/__mocks__/buildConfig.ts

Theme should be adjust in build-configs to accept high contrast theme on integreat
- add high contrast theme
- add colors necessary for high contrast theme
- make adjustments in other platforms to avoid error (we are implementing for now only for integreat)
- none
Fixes: #3186 
---

3186: Adjust theme for high contrast mode

---

web/src/components/PoiFilters.tsx
web/src/components/base/Checkbox.tsx

Fix misaligned checkbox for poi filter.
- Add min-width and align-items center to fix misaligned checkbox in poi filters
If using the checkbox in a smaller size than 20px, its now necessary to override the min-width as well.
Go to http://localhost:9000/testumgebung/de/locations and hit `Orte filtern`.
Fixes: #3132
---

3132: Fix misaligned checkbox

---

native/android/build.gradle

When starting the android app at integreat the build fails :
```
Dependency 'androidx.browser:browser:1.9.0-alpha02' requires libraries and applications that
depend on it to compile against version 36 or later of the
Android APIs.
```
- Defined androidXBrowser at `/android/build.gradle` with version 1.8.0.
None.
- Just start the app for integreat (you may remove all node_modules and re-install)
Fixes: #3204 
---

3204: Add androidXBrowser with defined version at build gradle

---

native/src/routes/SearchModal.tsx
native/src/routes/__tests__/SearchModal.spec.tsx
release-notes/unreleased/2928-search-duplicates.yml
shared/hooks/useSearch.ts
web/src/hooks/__tests__/useReportError.spec.tsx
web/src/hooks/useReportError.ts
web/src/routes/SearchPage.tsx
web/src/routes/__tests__/SearchPage.spec.tsx

Improve error reporting for the search and fix search problems with duplicated documents.
- Remove duplicates from documents before searching
- Report errors occurring in search
- Adjust root project code style
N/A
1. ~~Manually add a duplicated document before sanitizing in `useSearch`(L70):~~ See testing instructions by @LeandraH [here](https://github.com/digitalfabrik/integreat-app/pull/3200#pullrequestreview-2768038950).
2. Ensure that no error is thrown
3. Manually add a duplicated document after sanitizing in `useSearch`(L75):
```ts
.addAllAsync([...documents, documents[0]!])
```
4. Ensure that the error is caught and reported (i.e. logged in dev mode)
Fixes: #2928, #3192
---

2928: Improve error reporting and fix search with duplicates

---

web/src/components/ChatConversation.tsx
web/src/components/ChatMessage.tsx

This PR fixes two minor UI issues for the integreat chat.
- Only make messages as big as necessary
- Fix overflow for user icon
N/A
Checkout the chat and see that messages only take the required space anymore. Also check that there is no horizontal overflow caused by the user icon.
Fixes: N/A
---

Fix UI issues for chat

---

web/src/components/ThemeContext.tsx

This PR saves the state of the contrast theme in LocalStorage. 
- used LocalStorage Hook to save the state ('light' or 'contrast')
- none
Go to http://localhost:9000/testumgebung/de and see state being persistent. You can also try to enable the dark/contrast theme on your browser and check the page whether it immediately detects the enabled theme on your browser and keeps it persistent throughout the interaction.
Fixes: #3187 
---

3187: Save contrast theme in localStorage on web

---

native/src/@types/styled.d.ts
native/src/App.tsx
native/src/components/Header.tsx
native/src/components/ThemeContext.tsx
native/src/hooks/useThemeContext.tsx

This PR adds toggle implementation for contrast theme. The contrast theme toggle function is located in settings according to the figma design.
- ThemeContext.tsx was implemented and added to App.tsx
- useThemeContext.tsx hook was added to further use it in Header.tsx as a settings toggle function
-  none
- Run the native app
- See the toggle function in settings
- Toggle the `Contrast mode` and see that the theme changes to contrast/dark
Fixes: #3185 
---

3185: Add toggle implementation for contrast mode for native

---

build-configs/index.ts
web/src/components/ChatSecurityInformation.tsx

Data security popup not opening at Integreat chat for RTL languages.
- Just passed `isRtl` to `InformationTooltipContainer` and changed the x value to 95% to be on the opposite side when the language is RTL.
None.
-
- Go to [http://localhost:9000/muenchen/de'](http://localhost:9000/muenchen/de)
- Switch to Arabic language.
- Open chat.
- Click on the lock icon.
Fixes: #3218 
---

3218: ChatSecurityInformation popup fix for RTL Support

---

.circleci/config.yml
.circleci/src/jobs/deliver_web.yml
.circleci/src/workflows/commit_design_system.yml

Deliver 3231-design-system-web to future.integreat.app.
- Add temporary `deliver_design_system` workflow to deliver integreat-test-cms builds to https://future.integreat.app
N/A
N/A
Fixes: #3232
---

3232: Deliver 3231-design-system-web to future.integreat.app

---

native/src/@types/styled.d.ts
native/src/App.tsx
native/src/components/Header.tsx
native/src/components/ThemeContext.tsx
native/src/hooks/useThemeContext.tsx
web/src/components/__tests__/ContrastThemeToggle.spec.tsx

This PR adds test to contrast theme toggle function.It checks whether toggle button is rendered on small and desktop views as well as whether the toggle function toggles the theme type from light->contrast or vice versa.
- create test file ContrastThemeToggle.spec.tsx
- tested render on small and desktop views
- tested whether toggle button changes the theme type (light->contrast or vice versa)
Fixes: #3225 
---

3225: Add test to contrast theme for web

---

web/src/components/CityContentToolbar.tsx
web/src/components/Footer.tsx
web/src/components/MapAttribution.tsx
web/src/components/Pois.tsx
web/src/components/PoisDesktop.tsx
web/src/components/SharingPopup.tsx
web/src/components/StyledSmallViewTip.tsx
web/src/components/Toolbar.tsx
web/src/styles/Aside.css
web/src/styles/MapView.css

The toolbar got very crowded and broke things in a few places. This PR improves this by applying multiple changes.
- Change the order of toolbar items (pdf > feedback > share > tts > high contrast)
- Move copy url to share toolbar item
- Set a `max-width` and allow text wrapping for toolbar items
- Display less toolbar items for desktop pois to allow fitting in one row (hide the contrast mode for pois and tts for pois list)
- Remove/reduce aside left spacing to avoid overlap
- Fix contrast of footer on pois desktop
- Fix overlap of footer and zoom buttons on pois desktop
The contrast mode can't be toggled anymore from pois web.
Check the toolbar items in different languages/pages/screen sizes, e.g.:
- http://localhost:9000/testumgebung/de
- http://localhost:9000/testumgebung/mk/locations …

3195: Fix displaying of toolbar and toolbar items

---

.circleci/config.yml
.circleci/src/jobs/deliver_android.yml
.circleci/src/jobs/deliver_ios.yml
.circleci/src/jobs/promote_android.yml
.circleci/src/jobs/promote_ios.yml
native/android/app/buildConfigs.gradle
native/android/fastlane/Fastfile
native/fastlane/util.rb
native/ios/Integreat.xcodeproj/xcshareddata/xcschemes/aschaffenburg.xcscheme
native/ios/Integreat.xcodeproj/xcshareddata/xcschemes/integreat-e2e.xcscheme
native/ios/Integreat.xcodeproj/xcshareddata/xcschemes/integreat-test-cms.xcscheme
native/ios/Integreat.xcodeproj/xcshareddata/xcschemes/integreat.xcscheme
native/ios/Integreat.xcodeproj/xcshareddata/xcschemes/malte.xcscheme
native/run
package.json
tools/package.json
tools/yarn.lock
yarn.lock

This PR fixes the usage of the app-toolbelt both locally and in the CI.
- Add app-toolbelt also in the root package.json to be used locally and in all builds/deliveries/promotions using the build config
- Fix the usage of tools app-toolbelt in the CI (using `--cwd tools` over `workspace tools`). Installing the app-toolbelt twice allows us to save credits in the CI as installing it as a single dependency is substantially cheaper than installing all workspace dependencies while keeping it convenient for devs.
N/A
Test that building ios, building android and starting the bundler still (or again) works for you.
The CI was tested:
- builds: https://app.circleci.com/pipelines/github/digitalfabrik/integreat-app/13625/workflows/e1a7fa15-61a3-4e14-a39d-4e86db922d4c
- promotion (delivery is …

3262: Fix app-toolbelt usages

---

build-configs/BuildConfigType.ts
build-configs/ThemeType.ts
build-configs/aschaffenburg/index.ts
build-configs/aschaffenburg/theme/index.ts
build-configs/common/theme/colors.ts
build-configs/integreat/index.ts
build-configs/integreat/theme/index.ts
build-configs/malte/index.ts
build-configs/malte/theme/index.ts
build-configs/obdach/index.ts
build-configs/obdach/theme/index.ts
native/src/constants/__mocks__/buildConfig.ts
web/package.json
web/src/App.tsx
web/src/index.ejs
yarn.lock

This PR deprecates our old themes, adds material ui and its peer dependencies for web and sets up the new color palette for all build configs.
This should not be a breaking change.
- Deprecate the old theme/colors by renaming to legacy
- Add mui to web
- Add the new color palette for all build configs (a few values have to be clarified with UI/UX still)
I added a test button. Might be removed at a later point.
See the material UI button.
Feel free to check it out and play around with material ui.
Fixes: #3233, #3234
---

3233/3234: Setup mui and color palette

---

native/src/components/DatePicker.tsx
native/src/components/EventsDateFilter.tsx
native/src/components/__tests__/DatePicker.spec.tsx
translations/translations.json
web/src/components/DatePicker.tsx
web/src/components/EventsDateFilter.tsx
web/src/components/__tests__/DatePicker.spec.tsx

We had a missing translation key with some remnants in the translation.json.
For better accessibility I added new (and separate) translations for opening the calendar to select a start/end date.
Good catch @bahaaTuffaha!
- Add individual labels for date selection from calendar
- Remove old translations
N/A
Verify that there is no more warning and that the label is correct.
Fixes: N/A
---

Improve a11y for date selection in calendar

---

web/src/components/SearchInput.tsx

This proposal actually aligns the search input and the description below it without the need for any calculations with widths. Also, it increases usability on small devices by removing the excessive padding.

3199: Simplify styling

---

native/ios/fastlane/Fastfile
native/ios/fastlane/integreat/metadata/copyright.txt

The ios promotion is currently failing due to `command app-toolbelt not found`.
- Use the root app-toolbelt for the ios promotion
- Update copyright
N/A
N/A
Fixes: N/A
---

Fix ios promotion metadata command

---

web/src/components/base/RadioGroup.tsx

Currently in the malte help form the active radio box selection is not really good highlighted (white dot) inside white box.
Can be tested here: http://localhost:9000/testumgebung/de/gewaltschutz-kontakformular
- Just used `isContrastTheme` to switch between theme color (for contrast mode) and default color.
None.
- Go to any recurring event and click on export as iCal or go to http://localhost:9000/testumgebung/de/gewaltschutz-kontakformular at malte.
Fixes: #3307 
---

3307: Improve visibility of radio buttons

---

web/package.json
yarn.lock

Revert #3318 as this somehow [broke our web e2e tests](https://app.circleci.com/pipelines/github/digitalfabrik/integreat-app/13798/workflows/fd1771eb-5267-45e2-8dfe-46c1df5c3641/jobs/70677).
Probably some security alert. Should be fixed in #3288.
Run web e2e tests locally.
Fixes: N/A
---

Revert "Bump webpack-dev-server from 5.0.4 to 5.2.1" to fix web e2e tests

---

native/src/components/OrganizationContentInfo.tsx
web/src/components/OrganizationContentInfo.tsx

Fix domain and text and link color for organization info.
- Correctly display the domain of the organization url (native)
- Fix the text color for high contrast mode (native)
- Fix the link highlighting (web)
N/A
Go to https://webnext.integreat.app/testumgebung/de/elektronische-patientenakte-epa on both web and native.
Fixes: #3362
---

3362: Fix domain and text color for organization info

---

web/jest.setup.ts
web/src/components/Header.tsx
web/src/components/HeaderLogo.tsx
web/src/components/KebabMenu.tsx
web/src/components/NavigationBarScrollContainer.tsx
web/src/components/__tests__/HeaderLogo.spec.tsx
web/src/constants/dimensions.ts

Fix a small visual glitch related to Headroom; more specifically, on mobile, Headroom does hides less than expected of the Header when scrolling down.
* The height passed to Headroom was incorrect (since some padding was introduced at some point, which is not reflected in `dimensions.headerHeightX`).
This fixes this, and simplifies some of the Header related rendering / CSS.
* I also removed JS-based viewport-specific behavior, to avoid any flickering when the viewport changes.
Some slight changes in the layout (some slight horizontal shifts in the logo area)
In my view theses are improvements :D
* Check that exactly half of the header is hidden when scrolling down, on a mobile viewport.
* Check that the header works as expected also in larger viewport.
* Check that all whitelabeled' …

Use correct height for headroom

---

web/src/components/FilterToggle.tsx

The button to toggle the date filter in mobile Safari was blue, with this it's black again.
- Using the `theme.colors.textColor` even when we're not in high contrast mode
- None
Use an iPhone and check in its browser that the color is correct
Fixes: #3345 
---

3345: Fix color of date filter toggle in browser in iOS

---

native/src/components/SnackbarContainer.tsx
native/src/components/TtsPlayer.tsx
native/src/components/__tests__/SnackbarContainer.spec.tsx
native/src/components/__tests__/TtsContainer.spec.tsx

Fix safe area for absolute elements.
- Fix the safe area view for snackbar
- Fix the safe area view for tts player
N/A
Check the tts player and the snackbar on different devices.
Fixes: #3423 
---

3423: Fix safe area for absolute elements

---

native/jest.setup.ts
native/src/utils/__tests__/sentry.spec.ts

When you do `yarn test` it will say at the end `A worker process has failed to exit gracefully and has been force exited...` so the issue was sentry's mock.
- Moved sentry mock to jest setup file.
- Removed requireActual() no need for it.
None.
Test `yarn test`
Fixes: #3446
---

3446: Fix sentry tests

---

web/src/components/BottomActionSheet.tsx
web/src/components/CategoryListItem.tsx
web/src/components/CityContentFooter.tsx
web/src/components/CityContentHeader.tsx
web/src/components/CityNotCooperatingFooter.tsx
web/src/components/CitySelector.tsx
web/src/components/Collapsible.tsx
web/src/components/ConsentSection.tsx
web/src/components/Contact.tsx
web/src/components/GoBack.tsx
web/src/components/KebabActionItem.tsx
web/src/components/KebabMenu.tsx
web/src/components/List.tsx
web/src/components/ListItem.tsx
web/src/components/NearbyCities.tsx
web/src/components/NewsListItem.tsx
web/src/components/PoiDetails.tsx
web/src/components/PoiListItem.tsx
web/src/components/PoisDesktop.tsx
web/src/components/SearchListItem.tsx
web/src/components/Spacer.tsx
web/src/components/Toolbar.tsx

We currently have a few places where we make a divider line (e.g. the Toolbar and the ConsentSection). Let's instead use the one that Mui offers out of the box
- Replaced the following with Mui divider :
- hr components.
- Any `border-bottom` that used for creating a divider except the ones at `RemoteContentSandBox.tsx` and `SharingPopup.tsx`.
- At Spacer.tsx.
- In some cases I had to wrap the whole components with fragment. (the divider is allergic to flex containers).
- At `CityContentHeader.tsx` I used `KebabItemDivider` it could sound unnecessary instead of remapping it again with divider.
- This could affect alot of lists and components check test section for what to test 👇️
- Test the following components/pages:
- Poi lists.
- toolbar.
- Contact details.
- Consent section.
- News
- …

3373: Mui divider

---

native/package.json
native/src/components/CalendarRangeModal.tsx
native/src/components/Categories.tsx
native/src/components/DatePickerInput.tsx
native/src/components/EventsDateFilter.tsx
native/src/components/Feedback.tsx
native/src/components/FilterToggle.tsx
native/src/components/News.tsx
native/src/components/Page.tsx
native/src/components/PoiDetails.tsx
native/src/components/SearchInput.tsx
native/src/components/SettingItem.tsx
native/src/components/base/InputSection.tsx
native/src/components/base/TextButton.tsx
native/src/routes/Events.tsx
native/src/routes/TuNewsDetail.tsx
yarn.lock

Currently not all elements can be navigated easily with external keyboard (for ex. Bluetooth or usb), the problem still exists because of the WebView [(existing issue)](https://github.com/react-native-webview/react-native-webview/issues/2326) and cannot be fully fixed because of this, additionally TextInput from react-native has an  [issue](https://github.com/facebook/react-native/issues/31820) with focusing. Thus [react-native-external-keyboard](https://github.com/ArturKalach/react-native-external-keyboard) has been used to solve the issue with TextInput.
- Use react-native-external-keyboard to solve the issue with TextInput for now untill we switch to react-native 0.80.0 version where this issue has been fixed
- DatePickerInput.tsx has been fixed
- EventsDateFilter.tsx has been adjusted …

2172: Support external keyboard usage

---

native/ios/Integreat/AppDelegate.swift
native/src/components/RedirectContainer.tsx
native/src/hooks/useNavigate.ts
native/src/hooks/useNavigateToDeepLink.ts

Fix infinite loop of opening deep link by actually replacing instead of pushing the route.
The changed behavior of the infinite loop when opening a deep link in the same city/same language seem to be due to the redirect container still being mounted even after navigating to some other route (or at least the interval in RedirectContainer still fires). I worked around it by actually replacing the route instead of just pushing a new route which unmounts the redirect route and therefore prevents the infinite interval.
I am not sure where exactly the changed behavior is coming from, but there might have been some breaking changes in react-navigation v7:
https://reactnavigation.org/docs/upgrading-from-6.x/#the-navigate-method-no-longer-goes-back-use-popto-instead
- Replace the current route …

3455: Fix infinite loop of opening deep link

---

web/src/components/BottomActionSheet.tsx
web/src/components/Header.tsx
web/src/components/base/Input.tsx

This problem located at 3231-design-system-web about the bottom sheet getting under the headroom on smallViewport.
- Removed the z-index at the headroom.
- Changed the MuiInputLabel zindex to 0.
Hope none.
- Go to http://localhost:9000/testumgebung/de/kontaktformular (Malte).
- scroll down and look if the input labels are above the headroom (header).
- Test the POI bottom sheet.
Fixes: #3416
---

3416: Headroom z-index fix

---

native/src/components/I18nProvider.tsx
native/src/components/__tests__/I18nProvider.spec.tsx
release-notes/unreleased/3489-chinese.yml
translations/src/config.ts
web/src/components/I18nProvider.tsx
web/src/components/__tests__/I18nProvider.spec.tsx

Add chinese fallback to show chinese app translations.
- Add fallback from `zh` to `zh-CN`
- Add second fallback to the default language for fallback languages (translations only)
- ~~It seems like using a language slug fallback (i.e. from `zh` to `zh-CN`) breaks the fallback of missing translations to the default language (German), see e.g. http://localhost:9000/muenchen/zh and open the chat. `privacyPolicyInformation` is just displayed as is.~~ Fixed this by adding the default language as second fallback to all fallback languages.
Check http://localhost:9000/muenchen/zh and http://localhost:9000/oberhausen/zh and assure that the app is translated to Chinese.
Fixes: #3489
---

3489: Add chinese fallback to show chinese app translations

---

web/src/components/RemoteContent.tsx

This PR fixes the details directly closing.
- Wrap the dangerouslySetInnerHtml with `useMemo` to prevent rerenders
N/A
Go to https://webnext.integreat.app/muenchen/de/beratung-und-hilfe-4/beratung-und-hilfe-integration/migrationsberatung-f%C3%BCr-erwachsene-mbe and open/close details.
Fixes: #3517
---

3517: Fix details directly closing

---

web/src/components/TtsContainer.tsx
web/src/components/TtsHelpModal.tsx

When I click on Read aloud at any content page it takes about 5 seconds and if you clicked on other page like news or map it will crash.
- Created a state called `isInitializing` to show a backdrop with spinner while initializing.
- Lowered the `TTS_TIMEOUT` to 2 seconds.
- Changed  the color of BookIcon at the `TtsHelperModal` to the correct one and replaced legacy text color with palette one.
- None.
- For this test you need unsupported browser like brave or base chromium.
- Test Read aloud on any content page.
- Test it on small screens.
Fixes: #3524
---

3524: Fix Easy speech not initialized state

---

web/src/components/BottomNavigation.tsx

Remove bottom navigation labels on small screens.
- Remove bottom navigation labels on small screens and add an aria-label instead
This deviates from the mui defaults, see reasoning in the issue.
Check the bottom navigation bar in different screen sizes.
Fixes: #3556
---

3556: Remove bottom navigation labels

---

web/src/components/__tests__/DatePicker.spec.tsx

`yarn test` is failing at
```bash
FAIL  src/components/__tests__/DatePicker.spec.tsx
● DatePicker › handles date change correctly
expect(jest.fn()).toHaveBeenCalledWith(...expected)
- Expected
+ Received
- "2025-10-01T12:44:26.986+02:00"
+ "2025-09-01T12:44:26.986+02:00",
{"validationError": null},
Number of calls: 1
```
- Today is the 30th of September when it adds 1 day plus it will expect 1st of October not September this is clearly means that it selects the day from the same month `fireEvent.click(getByText(newValue.day))`.
- Just used fixed dates instead of `DateTime.now()`
- None.
- `yarn test` at web.
Fixes: #
---

Fix DatePicker test to use fixed date values

---

web/src/components/SearchFeedback.tsx
web/src/components/SearchListItem.tsx
web/src/components/__tests__/SearchFeedback.spec.tsx
web/src/components/__tests__/SearchListItem.spec.tsx
web/src/routes/SearchPage.tsx

Use mui components for search list and list items.
- Use mui components for `SearchListItem`
- Use mui list for search
- Extract search content to own component
- Icons are not displayed anymore
Check out the city content search.
Fixes: #3385
---

3385: Use mui components for search

---

web/src/components/Breadcrumb.tsx
web/src/components/Breadcrumbs.tsx
web/src/components/Tiles.tsx
web/src/components/__tests__/Breadcrumbs.spec.tsx
web/src/routes/CategoriesPage.tsx

Proposal PR to refactor the breadcrumbs to get rid of loads of custom logic and styling.
- Simplify breadcrumbs logic
- Remove most of the custom breadcrumb logic
- Only show one breadcrumb on small devices
- Remove highlighting of current breadcrumb
N/A
Checkout the breadcrumbs on different pages/screen sizes.
Fixes: N/A
---

[Proposal] 3376: Refactor breadcrumbs

---

web/src/components/ChatContainer.tsx
web/src/components/FeedbackToolbarItem.tsx
web/src/components/PoiFilters.tsx
web/src/components/Pois.tsx
web/src/components/TtsContainer.tsx
web/src/components/TtsHelp.tsx
web/src/components/TtsHelpModal.tsx
web/src/components/__tests__/ChatContainer.spec.tsx
web/src/components/__tests__/FeedbackContainer.spec.tsx
web/src/components/__tests__/PoiFiltersOverlayButtons.spec.tsx
web/src/components/__tests__/Pois.spec.tsx
web/src/components/base/Dialog.tsx

This PR fixes two small errors introduced in #3564.
It also removes the term `modal`.
- Fix aria-label
- Fix hydration error
- Remove naming `modal`
N/A
Check the console after opening the tts help modal.
Fixes: N/A
---

3513: Mui dialog fixes and renaming
